### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by jacknicklenson** [P-p-H-d/mlib#100]
Hi,
First thx for this library. I try to experiment with mlib but it gives me that error can you help me what is wrong with here ? I am new to this library sorry for noob question :/

![image](https://user-images.githubusercontent.com/90291236/162340904-14e18300-bd5f-4798-9b9a-659eb42f34c4.png)

**Comment by jacknicklenson** [comment]
Okey now i get it why it is not work i have to define : 
```c
_Bool cmp(node_s n1, node_s n2) {
  return (n1.w == n2.w && n1.h == n2.h);
}

ARRAY_DEF(arr_node, node_s, (CMP(cmp)))
```
 to know how to compare two custom data. thx anyway :)

**Comment by P-p-H-d** [comment]
By default, ARRAY_DEF expects to work on integer/float types, whereas a struct is used. Some operations are not possible on structures in C. So, the solution is to give the oplist responsible to handle POD struct to ARRAY\_DEF:
```
ARRAY_DEF(arr_node, node_s, M_POD_OPLIST)
```
This will use the C function memcmp to compare your structure.
Alternatively, you can also register globally the oplist of your node by defining the macro  M\_OPL\_node_s:
```
#define M_OPL_node_s() M_POD_OPLIST
ARRAY_DEF(arr_node, node_s)
```
This generates the same code.

```
_Bool cmp(node_s n1, node_s n2) {
  return (n1.w == n2.w && n1.h == n2.h);
}
ARRAY_DEF(arr_node, node_s, (CMP(cmp)))
```
There is an issue with this solution: the provided function is a matching method for the EQUAL operator, not for the CMP operator. The CMP operator expects a total order of the elements, like this:
```
int cmp(node_s n1, node_s n2) {
  return (n1.w < n2.w ? -1 : n1.w > n2.w ? 1 : n1.h < n2.h ? -1 : n1.h > n2.h);
}
ARRAY_DEF(arr_node, node_s, (CMP(cmp)))
```

**Comment by jacknicklenson** [comment]
hmmm very nice explanation,i see right now, thank you very much! :)
