### ISSUE TITLE
bitset: function for getting minimum index with bit set

### ISSUE THREAD

**Issue by dmlary** [P-p-H-d/mlib#105]
I'm trying to bitset to track unused pages in a large memory region, but I've run into a place where I can't find the functionality I'm looking for.  I couldn't find an easy/fast way to get the minimum index where the bit is set in the bitmap.

```c
bitset_resize(unused_pages, 6);
bitset_set_at(unused_pages, 3, true);
bitset_set_at(unused_pages, 4, true);
bitset_set_at(unused_pages, 5, true);
size_t index = bitset_unknown_function(unused_pages); /* should return 3; bitset_clz() returns 0 */
```

Is there a call path I'm missing in the docs or headers?  I've gone through both of them thoroughly and haven't found a way to do this.

### Things I've tried
* iterating through the bitmap is significantly slower than the internal traversal functions
* `bitmap_clz` both counts from the highest bit, and gives an index from the end; so bitmap is reversed from array
    * reluctant to go this route because must keep the bitmap reversal in mind when debugging; `bitset_get_str()` is reversed from actual page usage
```c
size_t index = bitset_clz(unused_pages);
bitset_set_at(unused_pages, bitset_size(unused_pages) - index - 1, false);
return pages[index]
```

### What I'm looking for
Stealing a bit from croaring, something like `roaring_bitmap_minimum()`.  https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring.h#L725-L729

What I'm looking to do:
```c
size_t index = bitset_minimum(unused_pages);
if (index == UINT64_MAX) { /* error */ }
bitset_set_at(unused_pages, index, false);
return &pages[index];
```

or ideally magic to find the lowest set bit, clear it, and return the index:
```c
size_t index = bitset_clear_lowest(unused_pages);
return (index == UINT64_MAX) ? NULL : &pages[index];
```

**Comment by P-p-H-d** [comment]
Indeed bitset_ctz is missing (count trailing zero) which is the equivalent of roaring_bitmap_minimum (See https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html )
I prefer it to your proposal of bitset_clear_lowest (doing bitset_ctz  + bitset_set_at will be as efficient).

**Comment by P-p-H-d** [comment]
bitset_ctz is available in master.

**Comment by dmlary** [comment]
Wow, thanks!  And thank you for the library as a whole!
