### ISSUE TITLE
Bug in list?

### ISSUE THREAD

**Issue by lindsaywhitney** [P-p-H-d/mlib#112]
If code is:

        list_test_data_it(u, l);
	list_test_data_next(u);
	printf("list len is %d\n", list_test_data_size(l));
	list_test_data_insert(l, u, w); 
	printf("list len is %d\n", list_test_data_size(l));
	list_test_data_remove(l, u); 
	printf("list len is %d\n", list_test_data_size(l));
	list_test_data_insert(l, u, w); 
	printf("list len is %d\n", list_test_data_size(l));
	list_test_data_remove(l, u); 
	printf("list len is %d\n", list_test_data_size(l));

run result is :

list len is 3
call testdata_init_set
list len is 4
call testdata_clear
list len is 2
call testdata_init_set
list len is 3
call testdata_clear
list len is 1

It seemed _insert is right, but _remove is wrong.

**Comment by P-p-H-d** [comment]
Thanks a lot for your report.

There was indeed an issue. Not in _remove, but in _insert.
It should be fixed in master.
