### ISSUE TITLE
Allocator customization

### ISSUE THREAD

**Issue by lavyadrian** [P-p-H-d/mlib#113]
Hey! My intended usage for the library requires that I be able to customize the used allocator. The manual provided mentions it can be done by overriding some macros, but I 'd very much like examples of how to do it provided if possible.
Thanks for any responses.

**Comment by P-p-H-d** [comment]
You can customize your allocator at two levels

* global level: before including any header, define the following macros:

```
// Allocate for single object
# define M_MEMORY_ALLOC(type) malloc (sizeof (type))
# define M_MEMORY_DEL(ptr)  free(ptr)
// Allocate for array of objects
# define M_MEMORY_REALLOC(type, ptr, n) realloc ((ptr), (n)*sizeof (type))
# define M_MEMORY_FREE(ptr) free(ptr)
```

* local level: when defining your container:
```
# define MY_MEMORY_ALLOC(type) malloc (sizeof (type))
# define MY_MEMORY_DEL(ptr)  free(ptr)
LIST_DEF(list_int, int, M_OPEXTEND(M_BASIC_OPLIST, NEW(MY_MEMORY_ALLOC), DEL(MY_MEMORY_DEL)))
```

I will add complete examples in the example folder later.

**Comment by P-p-H-d** [comment]
Examples of custom allocation have been added to master
