### ISSUE TITLE
How to define a set of pointer?  

### ISSUE THREAD

**Issue by lindsaywhitney** [P-p-H-d/mlib#116]
DICT_SET_DEF(set_int_ptr, int*, M_PTR_OPLIST)  
will report error.

**Comment by P-p-H-d** [comment]
Indeed, the reported errors indicate a missing method in the oplist
M_PTR_OPLIST doesn't define a HASH method for pointer. You need to define it. The POD hash may work. For example:

     DICT_SET_DEF(dict_setintptr, int*, M_OPEXTEND(M_PTR_OPLIST, HASH(M_HASH_POD_DEFAULT)))

Of course you need to tune your hash function according to your objects.
