### ISSUE TITLE
Missing explanation of how to access multiple values in a BPTREE_MULTI

### ISSUE THREAD

**Issue by BrianSipos** [P-p-H-d/mlib#121]
There is an explanation for how to declare a `BPTREE_DEF*` separately from a `BPTREE_MULTI_DEF*` and how it affects the storage logic and key uniqueness, but I don't see a way to actually access multiple values under the same key except for iterating over _all_ of the items in the tree (which would defeat the purpose of using a tree for fast lookup).

Is there a separate API for looking up a BPTREE iterator from a key, or some other way of accessing the multiple possible values within a `BPTREE_MULTI`? There may already be so, I just cant find any documentation or explanation of it.

**Comment by P-p-H-d** [comment]
You can use the following API to iterate on the multiple values associated to a key:

* name_it_from
* name_it_while_p

(I have fixed the documentation of name_it_from which was incorrect).
See [example](https://github.com/P-p-H-d/mlib/blob/master/example/ex-bptree02.c)

**Comment by BrianSipos** [comment]
Thanks! I thought it was just the docs and not the interface.
