### ISSUE TITLE
Documentation of and access to M-ARRAY being contiguous

### ISSUE THREAD

**Issue by BrianSipos** [P-p-H-d/mlib#123]
The current main documentation for M-ARRAY in the `README.md` does not explicitly state that the array allocation is contiguous in memory and there is no way to access the memory explicitly. From inspecting the source I can see this is the case currently, but having a stable guarantee would be nice.

https://github.com/P-p-H-d/mlib/blob/2c0db401583df8c36d57a923842d58316c5862c3/m-array.h#L182-L186

It would be nice if the documentation explained that the array guarantees contiguous memory and if there was a `name_data()` type access function similar to how `std::vector::data()` [operates](https://en.cppreference.com/w/cpp/container/vector/data).

**Comment by P-p-H-d** [comment]
Technically, the objects in the array may not be contiguous. Some padding may be present between each object (for example with `struct s{ char x[3]; }`

I don't see the point of having such an API (`std::vector::data`). Not that I don't have any plan to change the internal representation, but I really don't like such low level API that break encapsulation of a container.

Why do you need such an API or such a property?

**Comment by BrianSipos** [comment]
My actual desire is to have a sequential bytestring builder the same way that the `m_string_t` allows sequential text string building. I could do this with an M-Array of `uint8_t` but would need some stable way to use the raw array. I know this can be done today using non documented access but would prefer if there was a documented way.

Alternatively maybe some guidance about how an `m_string_t` could be used with non text data (e.g. what functions to avoid using) would also meet the desire.

**Comment by P-p-H-d** [comment]
I can see potential solutions

* A new API for array:

** void name_acquire_direct_access(type **ptr, size_t *size, name_t array) : acquire a direct access to the container array. While the direct access is acquires, *no* function of array can be called except :
** void name_release_direct_access(name_t array, type *ptr, size_t size); : release the direct access. The array functions works normally now.

I have yet to find how to make it works with the exception model. What should happen if an exception occurs within the direct access? Mmmmm.....

* Using a custom serializer for your needs? using _out_serial. I am not sure it will work.

* Allow \0 in strings. At first glance, several API fuctions already support it (even if the slow assertion fails, it is not enabled by default, only in test mode): string_init, string_init_set, string_equal, string_push_back, string_size, string_capacity, string_reserve, string_get_cstr, string_clear, string_clear_get_cstr, string_reset, string_set_char, string_empty_p, string_set, string_set_n, string_init_move, string_move, string_cat, string_left, string_right, string_mid, string_hash, string_get_str, string_parse_str, string_out_str, string_in_str, string_out_serial, string_in_serial,

**Comment by P-p-H-d** [comment]
Have you any preference?

**Comment by BrianSipos** [comment]
Similar to how M-DICT has two variants (one for dictionary and one for set logic) maybe the third option with a different set of `#define` for whatever functions are safe on byte strings would work.

Meaning something like
```c
#define bytestring_t m_string_t
#define bytestring_it_t m_string_it_t
...
#define bytestring_init m_string_init
#define bytestring_get_ptr m_string_get_cstr
...
```
and the like so that it looks like there is a bytestring struct but really it's just a set of names for the safe string functions. Whether it's in a different header with different documentation is up to you.

**Comment by CkovMk** [comment]
> Similar to how M-DICT has two variants (one for dictionary and one for set logic) maybe the third option with a different set of `#define` for whatever functions are safe on byte strings would work.
> 
> Meaning something like
> 
> ```c
> #define bytestring_t m_string_t
> #define bytestring_it_t m_string_it_t
> ...
> #define bytestring_init m_string_init
> #define bytestring_get_ptr m_string_get_cstr
> ...
> ```
> 
> and the like so that it looks like there is a bytestring struct but really it's just a set of names for the safe string functions. Whether it's in a different header with different documentation is up to you.

Got attracted by this topic when poking around. Being used mlib for some time, I'm really impressed by its design.

Vote +1 for this solution.

An separate bytestring will greatly ease the implementation of protocol buffers, etc. For a reference, Qt has QByteArray similiar to this concept, apart from having QVarLengthArray, QList and QString. QByteArray can hold any data, and can be converted to QString taking account of encoding.

**Comment by P-p-H-d** [comment]
Shall the bytestring container allow read only sequential byte or read/write sequential bytes?

**Comment by P-p-H-d** [comment]
Here is the proposed API for a bstring container:

```
bstring_t {
 size_t size, alloc, offset;
 unsigned char *ptr;
 bool direct_mode;
 }

void bstring_init(bstring_t x);
void bstring_init_set(bstring_t dst, const bstring_t src);
void bstring_set(bstring_t dst, const bstring_t src);
void bstring_clear(bstring_t x);
void bstring_init_move(bstring_t dst, bstring_t src);
void bstring_move(bstring_t dst, bstring_t src);

void bstring_reset(bstring_t x);
void bstring_reserve(bstring_t x, size_t capacity);

size_t bstring_size(const bstring_t x);
size_t bstring_capacity(const bstring_t x);

void bstring_push_back_char(bstring_t x, char c);
void bstring_push_back_uchar(bstring_t x, unsigned char c);
void bstring_push_back_bytes(bstring_t x, size_t n, const void *buffer);

void bstring_push_at(bstring_t x, size_t index, size_t n, const void *buffer);
void bstring_splice(bstring_t dst, bstring_t src);

void bstring_pop_back_char(char *c, bstring_t x);
void bstring_pop_back_uchar(unsigned char *c, bstring_t x);
void bstring_pop_back_bytes(size_t n, void *buffer, bstring_t x);

// NOTE: This  _pop_front is not optimized for circular buffer usage
void bstring_pop_front_char(char *c, bstring_t x);
void bstring_pop_front_uchar(unsigned char *c, bstring_t x);
void bstring_pop_front_bytes(size_t n, void *buffer, bstring_t x);

void bstring_pop_at(size_t n, void *buffer, bstring_t x, size_t index);

int  bstring_cmp(const bstring_t a, const bstring_t b);
bool bstring_equal_p(const bstring_t a, const bstring_t b);
bool bstring_empty_p(const bstring_t a);
size_t bstring_hash(const bstring_t a);

void bstring_set_uchar(bstring_t x, size_t position, unsigned char c);
unsigned char bstring_get_uchar(bstring_t x, size_t position);

const unsigned char *bstring_view(const bstring_t x, size_t offset, size_t size_requested);

// Acquire / release direct write access: once acquired, user can directly wite at the returned pointer for the requested size
// All other operations on the bstring are forbidden during direct access.
// This allows passing the bstring buffer to be formatted by different API
unsigned char *bstring_acquire_access(bstring_t x, size_t offset, size_t size_requested);
void bstring_release_access(bstring_t x);

// Iterator (useful?)
void bstring_it(bstring_it_t it, bstring_t x);
void bstring_it_last(bstring_it_t it, bstring_t x);
void bstring_it_end(bstring_it_t it, bstring_t x);
void bstring_it_set(bstring_it_t itd, bstring_it_t its);
bool bstring_end_p(bstring_it_t it);
bool bstring_lasp_p(bstring_it_t it);
bool bstring_it_equal_p(bstring_it_t it1, bstring_it_t it2);
void bstring_next(bstring_it_t it);
void bstring_previous(bstring_it_t it);
unsigned char *bstring_ref(bstring_it_t it);
const unsigned char *bstring_cref(bstring_it_t it);
void bstring_insert_v(bstring_t x, bstring_it_t it, size_t size, void *buffer);
void bstring_remove_v(bstring_t x, bstring_it_t it, size_t size);

// I/O stuff
void bstring_get_str(string_t str, const bstring_t x, bool append);
bool bstring_parse_str(bstring_t x, const char str[], const char **endp);
void bstring_out_str(FILE *out, const bstring_t x);
bool bstring_in_str(bstring_t x, FILE *int);
m_serial_return_code_t bstring_out_serial(m_serial_write_t f, const bstring_t x);
m_serial_return_code_t bstring_in_serial(bstring_t x, m_serial_read_t f);
```

**Comment by BrianSipos** [comment]
> Here is the proposed API for a bstring container:

I think this API is quite good and covers many possible manipulations including the pushing and popping of multi-byte chunks. Having the "view" and the "direct" access is also a nice convenience.

I would also be happy if all of the storage and public access used `uint8_t` and didn't provide alternate `char` versions. But maybe that is generally useful for someone else.

**Comment by P-p-H-d** [comment]
The Byte string has been implemented and should be complete.
