### ISSUE TITLE
Inconsistency in I-LIST use of OPLIST

### ISSUE THREAD

**Issue by BrianSipos** [P-p-H-d/mlib#125]
The current [I-LIST](https://github.com/P-p-H-d/mlib/blob/master/README.md#m-i-list) use of the OPLIST provided to `ILIST_DEF()` is a little inconsistent, and it's difficult to see how a struct implementing the `ILIST_INTERFACE()` is supposed to make use of the `INIT` and `CLEAR` operations. The example in the I-LIST section of the README does not make use of those operations and neither do the tests in [`test-milist.c`](https://github.com/P-p-H-d/mlib/blob/master/tests/test-milist.c)

The one immediate inconsistency is that two `M_CALL_CLEAR()` uses below have one dereferencing a pointer-to-struct and the other not.
https://github.com/P-p-H-d/mlib/blob/0f7d5bf366aa730e6247a0452f264510cb6d9ed9/m-i-list.h#L222 https://github.com/P-p-H-d/mlib/blob/0f7d5bf366aa730e6247a0452f264510cb6d9ed9/m-i-list.h#L520

Since the I-LIST does not copy struct instances, I think the OPLIST functions using the struct need to pass-by-pointer. The array-of-1 trick used elsewhere in M*LIB does not appear to work with I-LIST due to the way that the `ILIST_INTERFACE` declared member is accessed. This would also affect the `_insert()` function here also
https://github.com/P-p-H-d/mlib/blob/0f7d5bf366aa730e6247a0452f264510cb6d9ed9/m-i-list.h#L536

**Comment by BrianSipos** [comment]
Alternatively, the (many and frequent) access to the `obj->name` could themselves be embedded in the OPLIST to allow both direct struct-instances-in-list as well as other strategies such as
```c
ILIST_DEF(ilist_tname, test_t *)
```
but that is more invasive and I don't have a specific use case for it.

**Comment by P-p-H-d** [comment]
It is indeed serious bugs! Thanks for the reports.

I think both bugs are fixed on master, with an example.
I have changed the prototype and semantic of the _insert_ method for intrusive lists, so that it reflects more the policy of  other functions (i.e. no allocation, and you give away your object to the list).
