### ISSUE TITLE
How to define custom malloc and free function in m-i-shared

### ISSUE THREAD

**Issue by lindsaywhitney** [P-p-H-d/mlib#127]
How to define custom malloc and free function in m-i-shared?
Can define like this?
ISHARED_PTR_DEF(ishared_data, struct data_s, ( NEW(API_2(new_data)) , DEL(API_2(del_data) ) )

**Comment by P-p-H-d** [comment]
I am not sure what are doing your new_data or del_data functions but it looks like more like INIT & CLEAR.

In M\*LIB, there is a difference between INIT (initialize an object) and NEW (allocate the space needed for an object). Usually to construct an object on the heap, it performs NEW() to allocate the dynamic memory of the object, then INIT() to initialize this object. To destroy an object, it calls CLEARS to destruct the object and then DEL() to free the memory.

Anyway if you want to use NEW & DEL, here is an example:

```
#include "m-i-shared.h"

struct data_s {
  M_ISHARED_PTR_INTERFACE ( ishared_data, struct data_s);
  int x;
};

#define new_data(type) malloc(sizeof (type))
#define del_data(p)    free(p)

ISHARED_PTR_DEF(ishared_data, struct data_s, M_OPEXTEND(M_POD_OPLIST, NEW(new_data) , DEL(del_data) ) )

```

NEW will create the function struct data_s *ishared_data_new(void) that will create a new object on the heap.
DEL will perform automatically the release of the memory when the shared pointer is 'destroyed'
The default of NEW / DEL is to use the heap memory which is the default (and is exactly like the example above).

If you want to use it on static objects only (no dynamic allocation), you have to disable NEW & DEL 
```
ISHARED_PTR_DEF(ishared_data, struct data_s, M_OPEXTEND(M_POD_OPLIST, NEW(0) , DEL(0) ) )
```
You cannot mix both behaviors.
