### ISSUE TITLE
Documentation for M-BPTREE does not match all functions

### ISSUE THREAD

**Issue by BrianSipos** [P-p-H-d/mlib#128]
The documentation for [M-BPTREE specialized methods](https://github.com/P-p-H-d/mlib/blob/master/README.md#specialized-methods-7) indicates that there is a `name_pop()` function with a void return type. But the actual source currently has a `name_pop_at()` with a bool return type. I didn't spend time to audit the other interface functions but I was making use of this one.

The documentation should agree with the desired public API functions.

**Comment by P-p-H-d** [comment]
Indeed, the documentation was not correct. I have fixed it, and check other specialized functions.
