### ISSUE TITLE
M-SHARED pointer cannot use forward-declared type

### ISSUE THREAD

**Issue by BrianSipos** [P-p-H-d/mlib#129]
I have a need for a managed-lifetime struct with recursive references, so I was hoping to be able to use the M-SHARED container to implement this but it appears that M-SHARED requires a fully-defined struct due to its optimization using the "combine_s" struct.

It could be good to include this detail in the README interface documentation. If there could be a way to avoid the use of that combine mechanism for forward declared structs that would be helpful in the longer-term.

**Comment by P-p-H-d** [comment]
The definition of the combine_s structure can easily be deactivated if the INIT and EMPLACE_TYPE operators are disabled (This will prevent the definition of `_init_new` and the `_emplace` functions). Is such change sufficient for you?
