### ISSUE TITLE
dictionary of pointers (LUT) vs compilers behavior

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#17]
I'm trying to create a LUT (look up table) that maps a string to a generic pointer. I can compile and use the following minimal example with gcc (8.1.1) without errors/warnings:
```
#include <m-dict.h>
#include <m-string.h>
#include <stdio.h>

DICT_DEF2(lut, string_t, STRING_OPLIST, const void *, M_DEFAULT_OPLIST)

int main() {
    lut_t lut;
    string_t label;
    int a = 10;

    lut_init(lut);
    string_init(label);

    string_set_str(label, "a key");
    lut_set_at(lut, label, NULL);

    string_set_str(label, "another key");
    lut_set_at(lut, label, &a);

    string_clear(label);
    lut_clear(lut);
}
```

but here I was forced to use `const void*` instead of, a more useful for me, `void *` because of some errors with gcc like:
```
../test/test-mlib.c: In function ‘lut_cget’:
../custom-libs/include/m-core.h:1334:49: warning: returning ‘const void **’ from a function with incompatible return type ‘void * const*’ [-Wincompatible-pointer-types]
   (((union { type *ptr; const type *cptr; }){n}).cptr)
...
```

using `void *` with clang I get a different (maybe equivalent) error:
```
../test/test-mlib.c:5:1: warning: returning 'const void **' from a function with result type 'void *const *' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
DICT_DEF2(lut, string_t, STRING_OPLIST, void *, M_DEFAULT_OPLIST)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-dict.h:39:3: note: expanded from macro 'DICT_DEF2'
  DICTI_DEF2_P1(M_IF_NARGS_EQ1(__VA_ARGS__)                             \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../custom-libs/include/m-dict.h:111:28: note: expanded from macro 'DICTI_DEF2_P1'
#define DICTI_DEF2_P1(arg) DICTI_DEF2_P2 arg
                           ^~~~~~~~~~~~~~~~~
```

finally, if I rollback to `const void*` with clang it works but I can't get rid of this annoying warning:
```
../test/test-mlib.c:5:41: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
DICT_DEF2(lut, string_t, STRING_OPLIST, const void *, M_DEFAULT_OPLIST)
```

A side note: I was trying to create containers with pointers to other types (like mpz) but the default OPLIST with generics (gnu11) can't clearly manage the out_str method. I'm not interested in printing the linked structure (the raw pointer would be good) but I don't want to define a new out_str method every time. On the other side, using `void *` I have to cast to the correct type the pointer every time I extract something from the LUT. I hope it is clear what I mean.

Thanks.

**Comment by P-p-H-d** [comment]
1) For the reported issue, there was indeed in error in the implementation of the M_CONST_CAST. It has been fixed in master, and you can use it like you want.

2)  For the side note, if you don't want to define a new out_str for each pointer you can define the dictionary by overloading the OUT_STR (& HASH) methods of the value type to support them only as  pointers like this:


```
#define HASH_AS_GENERIC_POINTER(x)      m_core_hash((const void*) &(x), sizeof (x)) 
#define FPRINT_AS_GENERIC_POINTER(f, x) fprintf(f, "%p", (void*)x)
#define GENERIC_PTR_OPLIST M_OPEXTEND(M_DEFAULT_OPLIST, OUT_STR(FPRINT_AS_GENERIC_POINTER),HASH(HASH_AS_GENERIC_POINTER))

DICT_DEF2(lut, string_t, STRING_OPLIST, mpz_t *, GENERIC_PTR_OPLIST)
```

**Comment by diraimondo** [comment]
Ok, thank you for the fix and for the hint!

I'm just wondering because we need the HASH method for the pointer. Should it be necessary only for the key type? Just for curiosity...

Thanks

**Comment by P-p-H-d** [comment]
Yes, it is only needed for the key type. 
However the method HASH is defined for the default oplist,and it is not well supported with a void * in C11 mode. So it is redefined to avoid a warning.
