### ISSUE TITLE
[feature request] multiple heterogeneous M_LET with a single macro/block

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#18]
I'm starting to heavily using M_LET and M_EACH macros. The first one is very useful to keep the code minimal and to forget about init/clean dues. 
Using it in block that declare many M*LIB container instances  it happens that the block got too many nesting levels: sometimes this badly squeeze the code. In my case is forced by the automatic use of beautification tools like clang-format inside the editor.

I appreciate the possibility to declare with M_LET multiple instances with the same type. I'm wondering if it could be possible to have a macro (maybe M_LET itself) that is able to declare multiple instances of heterogeneous types. This would permit to concentrate in a single block all the necessary containers.

Something like: `M_LET ((x1, x2, type1_t), (y1, type2_t), (z1, z2, z3, type3_t)) { /* code */ }`

**Comment by P-p-H-d** [comment]
You can already use multiple M_LET with a single block. It may do what you want:

```
int main(int argc, const char *argv[])
{
  M_LET(arr, array_string_t)     
  M_LET(dict, dict_mph_t)     
  M_LET(seed, array_seed_t)
  M_LET(value, array_value_t) {
    const char *filename = (argc > 1) ? argv[1] :"/usr/share/dict/words";
    dict_read_from_file(dict, arr, filename);
    CreateMinimalPerfectHash(seed, value, dict);
    test(seed, value, dict);
  }
  return 0;
}
```

You can also put them in the same line (I have updated master to avoid a warning in this case):

```
int main(int argc, const char *argv[])
{
  M_LET(arr, array_string_t)  M_LET(dict, dict_mph_t) M_LET(seed, array_seed_t)   M_LET(value, array_value_t) {
    const char *filename = (argc > 1) ? argv[1] :"/usr/share/dict/words";
    dict_read_from_file(dict, arr, filename);
    CreateMinimalPerfectHash(seed, value, dict);
    test(seed, value, dict);
  }
  return 0;
}
```

Will that do the work?

**Comment by diraimondo** [comment]
Yes, it works! It was there: I feel a bit stupid. :-)

Again, thanks.
