### ISSUE TITLE
IN_STR method missing on array

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#25]
As specified by documentation and confirmed by a quick look at the code in `m-array.h`, the container should provide the IN_STR method if the elements support it. This doesn't work in my tests.

```
ARRAY_DEF(my_list, string_t)
#define MY_LIST_OPLIST ARRAY_OPLIST(my_list, STRING_OPLIST)
#define M_OPL_my_list_t() MY_LIST_OPLIST

int main() {
    M_LET(list, list2, my_list_t)
    M_LET(string, string_t) {
        string_set_str(string, "hello");
        my_list_push_back(list, string);
        my_list_push_back(list, string);
        FILE *file = fopen("/tmp/test.data", "w+");
        assert(file);
        my_list_out_str(stdout, list);
        my_list_out_str(file, list);
        rewind(file);
        my_list_in_str(file, list2); /* <= not available :-( */
        my_list_out_str(stdout, list2);
        fclose(file);
    }
}
```
The same happens if I define an array of C native types like `int`. I didn't check with other types of container.

Sorry to bother you with these reports. Heavily using it into an extensive project such defects come up.

**Comment by diraimondo** [comment]
I'm noting that the documentation usually reports wrong prototypes for the _in_str methods: the destination container is sometimes reported as second element (maybe a copy&paste from _out_str) and, other times, with the const specification.

**Comment by P-p-H-d** [comment]
I see a bug in your example. You shall write:
`my_list_in_str(list2, file); `
once I fix this, your example compiles & runes fine.
All functions have the out parameter first. The documentation is wrong), it shall be:
void name\_in\_str(name\_t array, FILE *file)

C native types do not support generic IN_STR method yet!

**Comment by diraimondo** [comment]
Ok, documentation fooled my on first glance. You can keep this report se request for C native types support and for documentation fix.

**Comment by P-p-H-d** [comment]
Both have been taken in master. 

Good luck for your project!

**Comment by diraimondo** [comment]
On some early tests it looks that the `_get_str` methods for C native types work well. Thank you.
