### ISSUE TITLE
binary serialization

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#26]
I was thinking if some kind of "binary serialization" on the model of `get_str/parse_str` could be possible. It would be a great feature from the application point-of-view: binary representation is more bandwidth-efficient if used on network communications. 
Given that I'm not sure if this is out of the scopes of the library or if you are interested in this.

It could be a m*lib specific representation or you could even think to some standards like https://msgpack.org/ or https://developers.google.com/protocol-buffers/.

Consider this just a feature request and feel free to close it if it doesn't make sense for you.

**Comment by P-p-H-d** [comment]
Proper binary serialization will need to define integer endianess, type sizes (that may differ on different targets), il we enable reading/writing from other machine or only on the same architecture. It will also need proper algorithms for the parser to enable much faster read (dictionary or binary tree parsing is not optimized in the reading case) with pretty much no work to do.

MSGPACK & PROTOBUF are more like a compact serialization. I get bad experience with PROTOBUF. I didn't know MSGPACK. I will look at it.

**Comment by diraimondo** [comment]
Yes, do a proper binary serialization is not straightforward. I would suggest to bridge m*lib with another lib like MSGPACK. Maybe using another buddy library to use with m*lib. It should be easier.

**Comment by P-p-H-d** [comment]
The objective of MSGPACK is, in my opinion, first to transfer structures to others with their definition (like JSON or XML), and then to be more compact than JSON.

As M*LIB serialization doesn't transfer the definition, it is even smaller for the example  { "Compact": true, "schema": 0 } :
JSON: 27 bytes,
MessagePack: 18 bytes
M*Lib is (1,0): 5 bytes
This depends on your ratio of tuple.

The ratio MSGPACK/JSON seems to be a little bit more than 50%.

**Comment by P-p-H-d** [comment]
It will be good to have import/export methods to the XML/JSON/MSGPACK/PROTOBUF/BINARY format. And maybe other. However, I don't plan to add all of them in the M*LIB containers. 

Instead, I think of adding a generic interface for the serialization of data that may be customized by the user to perform the import/export of objects in whatever format they want into what they want (FILE/memory/...). To simplify it, this interface could only support one kind of import/export per compilation unit.

**Comment by diraimondo** [comment]
I'll available to test the new interface when it will come.

**Comment by P-p-H-d** [comment]
I am glad to say that the generic serialization is at least available in master!

New objects have been added:
- m_serial_read_t: generic object that enables to perform serial read.
- m_serial_write_t: generic object that enables to perform serial write.

Theses objects have a pointer to a constant interface that provided the needed generic interface of the object with the callback to use (like a C++ virtual interface):
- m_serial_read_interface_t: interface an object has to provide for enabling input serialization. 
- m_serial_write_interface_t: interface an object has to provide for enabling output serialization.

I try to make the interface mature enough to enable any serialization to work. The interface has to provide the following input / output methods of the following objects:
* boolean
* integer 
* float 
* string
* array
* map
* tuple
* variant

Any containers has to use theses available methods for its own serialization. I may add further methods later (like in / out enumerate).

New classic methods have been added to the containers and their oplists:
- _out_serial(m_serial_write_t s, object): write object into the serial 
- _in_serial(object, m_serial_read_t s): read object from the serial

Default types have theses methods available when building for C11.

An instance of the interface is available that perform import / export to JSON: m-serial-json.

Example of output:
```
 FILE *f = fopen ("a-mjson.dat", "wt");
  if (!f) abort();
  m_serial_json_write_init(out, f);
  ret = my2_out_serial(out, el1);
  assert (ret == M_SERIAL_OK_DONE);
  m_serial_json_write_clear(out);
  fclose(f);
```

Example of input:
```
  f = fopen ("a-mjson.dat", "rt");
  if (!f) abort();
  m_serial_json_read_init(in, f);
  ret = my2_in_serial(el2, in);
  assert (ret == M_SERIAL_OK_DONE);
  m_serial_json_read_clear(in);
  fclose(f);
```

**Comment by diraimondo** [comment]
Great! I'll test it when I get free time. Are you going to release an instantiation with an efficient binary serialization?

**Comment by P-p-H-d** [comment]
I have some ideas for a binary serialization indeed. 
How do you qualify efficient? Speed of import/export? Size of the exported data?

**Comment by diraimondo** [comment]
@P-p-H-d I'm personally interested in efficient import/export functions (less time to manage format conversion) but I guess there are cases where the space efficiency would be more interesting.

**Comment by P-p-H-d** [comment]
m-serial-bin is available in master
