### ISSUE TITLE
a proper way to break from a M_LET block

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#29]
In order to respect the following understandable claim about M_LET usage:
```
NOTE: The user code can not perform a return or a goto outside the {} otherwise the clear code of the object won't be called .
```
it is often necessary to write pedantic and inelegant code inside. It would be great to have an official way to "break" from such code jumping at the end in a proper way. Something like a new M_BREAK macro that will not break in the future release (not a simple trick).

**Comment by P-p-H-d** [comment]
Strangely the keyword 'continue' performs what you want...
Not sure I want to support it without a proper encapsulation since it is confusing. 
I'm still thinking about it.

**Comment by diraimondo** [comment]
A simple way would be to insert in the M_LET macro expansion a label at the end of the block and to declare M_BREAK as a goto to such label.

In such way we can use "horrible gotos" without showing it... :-)

**Comment by P-p-H-d** [comment]
If you use master, you can use the standard keyword 'break' to break properly from a M_LET block.
