### ISSUE TITLE
attempt to redefine parse_str for an enum

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#31]
I was trying to define a type from an enumeration but with a more informative output on the `out_str/in_str/get_str/parse_str` methods. Instead of a plain number something like `number-SOME_TEXT`.
I faced some problems on the OPLIST definition, indeed the methods works but I can't use such type in other containers. I can't spot the problem.

The toy example follows:
```
#include <m-string.h>
#include <m-tuple.h>
#include <stdio.h>

typedef enum { RED = 0, WHITE, BLUE, BLACK } color_t;
const char *color_str[] = {
    [RED] = "red", [WHITE] = "white", [BLUE] = "blue", [BLACK] = "black"};

#define color_out_str(f, x) (fprintf(f, "%u-%s", x, color_str[x]))
#define color_in_str(x, f) (fscanf(f, "%u-%*[a-z]", &x))
#define color_get_str(s, x, a)                                                 \
    ((a ? string_cat_printf : string_printf)(s, "%u-%s", x, color_str[x]))
bool color_parse_str(color_t *ptr, const char str[], const char **endptr) {
    char *end;
    *ptr = strtoul(str, &end, 10);
    if (end != str) {
        if (*end != '-')
            return false;
        end++;
        const char *ptr2 = color_str[*ptr];
        while (*ptr2 != '\0' && *ptr2 == *end) {
            ptr2++;
            end++;
        }
        if (endptr != NULL)
            *endptr = end;
        return (*ptr2 == '\0');
    } else
        return false;
}
#define COLOR_OPLIST                                                           \
    M_OPEXTEND(M_DEFAULT_OPLIST, OUT_STR(color_out_str), IN_STR(color_in_str), \
               GET_STR(color_get_str), PARSE_STR(color_parse_str))
#define M_OPL_color_t() COLOR_OPLIST

TUPLE_DEF2(my_tuple, (name, string_t), (color, color_t))
#define MY_TUPLE_OPLIST TUPLE_OPLIST(my_tuple, STRING_OPLIST, COLOR_OPLIST)
#define M_OPL_my_tuple_t() MY_TUPLE_OPLIST

int main() {
    color_t color = WHITE, color2;
    M_LET(string, string_t) {
        color_out_str(stdout, color);
        fputc('\n', stdout);
        color_get_str(string, color, false);
        assert(color_parse_str(&color2, string_get_cstr(string), NULL));
        printf("%u -> %s -> %u\n", color, string_get_cstr(string), color2);
        string_set_str(string, "2-wrong");
        assert(!color_parse_str(&color2, string_get_cstr(string), NULL));
    }
}
```

I'm getting a warning like `incompatible integer to pointer conversion passing 'color_t' to parameter of type 'color_t *'; take the address with & [-Wint-conversion]` on the tuple definition.

**Comment by P-p-H-d** [comment]
I get the following warning when I try your code:
```
error: incompatible type for argument 1 of ‘color_parse_str’
                GET_STR(color_get_str), PARSE_STR(color_parse_str))
```
Indeed, color_parse_str expects a T* instead of a T:
`bool color_parse_str(color_t *ptr, const char str[], const char **endptr) {`
So your association between the operator and the method in the oplist shall be defined as:
`PARSE_STR(color_parse_str M_IPTR)`
(Or use API_2 later but it is still WIP)

**Comment by diraimondo** [comment]
I think the warning is different because I was using clang. 
I'm not sure to understand your explanation. In m-core.h I can see parse_str methods where the first argument is something like `type *`. Maybe this work if type is a M-LIB container (so an array[1]-type) but I can't imagine how to manage it with a native type.
Can you give some hint who to manage this using the actual API? Thanks

**Comment by diraimondo** [comment]
Ok, sorry I spotted only now the note on the usage of the M_IPTR keywork in the OPLIST definition.

I'm wondering what's the aim the API_2 mechanism.

**Comment by P-p-H-d** [comment]
The API_* mechanism is a more general mechanism to adapt the call of the operator to the needs of the methods. It defines how to call effectively the method:
```
void method_by_ref(type out, ...);           // API_0
void method_by_addr(type *out, ...);     // API_2
out = method_by_ret_value(...);            // API_4
```
API is not the right term for this, but I wasn't able to find the right term. API CALL ?
It is a WIP as it is not supported by all the library yet.

M_IPTR is the current way of doing it. But I wasn't able to generalize the trick used for this to support the method_by_ret_value.

In your example, you just need to write:
 
```
#define COLOR_OPLIST                                                           \
    M_OPEXTEND(M_DEFAULT_OPLIST, OUT_STR(color_out_str), IN_STR(color_in_str), \
               GET_STR(color_get_str), PARSE_STR(color_parse_str M_IPTR))

```

**Comment by diraimondo** [comment]
Ok, many thanks.
