### ISSUE TITLE
buffer inside another container?

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#34]
I've defined a buffer (as queue) of elementary types but it looks I can't use it inside another container (a tuple). Maybe this is related to the fact that I was not able to find a macro like BUFFER_OPLIST to define the respective oplist.

I want to do something like:
```
BUFFER_DEF(int_queue, int, 10,
           BUFFER_QUEUE | BUFFER_BLOCKING | BUFFER_THREAD_SAFE,
           M_DEFAULT_OPLIST)
TUPLE_DEF2(my_tuple, (a_queue, int_queue_t), (a_number, int))
```

**Comment by P-p-H-d** [comment]
As you may have noticed, the last lines of m-buffer are:
```
// NOTE: SET & INIT_SET are deliberately missing. TBC if it the right way.
// NOTE: There is no oplist defined for this container.

```
In fact, the queue as a synchronization should be a global variable. so I was thinking if it made sense to encapsulate it into another container. But maybe for tuple, it makes sense and I am overthinking :)

**Comment by diraimondo** [comment]
I got several threads that share a bunch of structures (to be accessed in a safe way). They are not defined as global variables as I don't like their use (except when it is strictly necessary): I would define a structure (but  I would use a tuples as substitute) that is passed by reference to the thread functions. This means that I would require the SET/INIT_SET methods and the possibility to embed buffers inside another containers. Tell me what do you think about such use and if you are going to implement such possibility. Otherwise I can clearly revert on a classic structure.

**Comment by P-p-H-d** [comment]
Ok for implementation.

**Comment by diraimondo** [comment]
I worried by the presence of the size parameter in the init method of a buffer. How can it be recursively managed by the init method of the container?

**Comment by P-p-H-d** [comment]
I plan to support only size defined at compilation time (and create a specialized initialize function that takes only the buffer as argument).

**Comment by P-p-H-d** [comment]
The methods INIT & INIT_SET have been done for the buffer, including the BUFFER oplist.
But I still have a constness issue to solve before considering the ticket as closed.

**Comment by P-p-H-d** [comment]
It should work now in 'master'.

**Comment by diraimondo** [comment]
Yes, it looks to work. Thank you.
