### ISSUE TITLE
Minor issues using m-array.h and m-concurrent.h

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#40]
Trying to write an ad-hoc benchmark for https://github.com/P-p-H-d/mlib/issues/39 I spotted few minor issues trying to get a thread-safe array container:
- there is a const-related warning, example: 
```
ARRAY_DEF(key_list, string_t)
#define M_OPL_key_list_t() ARRAY_OPLIST(key_list, STRING_OPLIST)
CONCURRENT_DEF(key_list_ts, key_list_t)
```
- the method `_size` is not exposed in the concurrent version: I can't get the number of elements in such kind of array.

**Comment by P-p-H-d** [comment]
Both issues should be fixed in master.

**Comment by diraimondo** [comment]
Now I'm getting at runtime an assertion error on the CONCURRENT_DEF point: `key_list_ts_read_lock: Assertion `out->self == out' failed.`

**Comment by P-p-H-d** [comment]
You forget to init keys. You should add in  main:

  key_list_ts_init(keys);
 ....
  key_list_ts_clear(keys);

**Comment by diraimondo** [comment]
Yes: stupid error. I didn't use such container on first runs because of other bug. On the other side it worker on some runs before but I was just lucky (maybe you added further controls on last commits).
