### ISSUE TITLE
for M_EACH cycles and clang-format: a strange behavior

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#42]
I'm used to heavily use automatic formatting of my code (on save). At the moment I'm using `clang-format` inside Atom. I had no problem with M*LIB expect for the `for M_EACH(...)` block. `clang-format` doesn't correct the indentation level of such block (it is untouched): I have to move it on the right column. This is funny.

Example: `clang-format` is not able to correct the excessive indentation of the `for M_EACH(...)` block.
```
    M_LET(list, insertion, my_list_t) {
        //
                                        for
                                            M_EACH(item, list, my_list_t) {
                                                //
                                                //
                                            }
    }
```

**Comment by P-p-H-d** [comment]
I don't know why it does it. 
You should ask clang-format maintainer.

**Comment by P-p-H-d** [comment]
I have played with all formatting options of clang-format. I didn't succeed in changing this strange behavior.

**Comment by P-p-H-d** [comment]
Bug report opened in clang-format:
https://bugs.llvm.org/show_bug.cgi?id=40480

**Comment by diraimondo** [comment]
I can see you bug report con clang-format but I'm wondering if it is related to the missing tab adjustment in opening post of this report.
