### ISSUE TITLE
mempool usage

### ISSUE THREAD

**Issue by diraimondo** [P-p-H-d/mlib#45]
This is a question about the way to use mempool. 
I can spot in the main documentation that it is possible to automatically use mempool structures associated to some type of linked list and that they are declared as thread-unsafe.
I can also see an header `m-c-mempool.h` and it looks related to the future lock free lists.

Now my question: I use on different threads many temporary containers (of some few types) that I usually create/destruct with macro M_LET. I'm wondering if it could be possibile to specify a mempool (specific per container type) to automatically use on such contexts. If they are thread-safe, they could be shared among threads or one-per-thread if unsafe.

**Comment by P-p-H-d** [comment]
You can qualify the mempool with M_THREAD_ATTR (or __thread or _Thread_local)  to create mempool variables unique for each thread like this:

```

extern int rand_get(void);
extern int g_result;

LIST_DEF(list_uint, unsigned int, (MEMPOOL( list_mpool), MEMPOOL_LINKAGE(M_THREAD_ATTR )))

void test_list (size_t n)
{
  M_LET(a1, a2, LIST_OPLIST(list_uint)) {
    for(size_t i = 0; i < n; i++) {
      list_uint_push_back(a1, rand_get() );
      list_uint_push_back(a2, rand_get() );
    }
    unsigned int s = 0;
    list_uint_it_t it1, it2;
    for(list_uint_it(it1, a1), list_uint_it(it2,a2); !list_uint_end_p(it1); list_uint_next(it1), list_uint_next(it2)) {
      s += *list_uint_cref(it1) * *list_uint_cref(it2);
    }
    g_result = s;
  }
}

void *thread(void*)
{
  list_uint_mempool_init(list_mpool);
  ...
  test_list();
  ...
  list_uint_mempool_clear(list_mpool);
}

```

I haven't tested this solution myself, but I don't see why it could not work. The drawbacks may be:

* You will have to initialize the mempool for each thread
* If nodes can be seen from other threads, you need to destroy all mempools at the same time.
* you have more memory consumption.
* the lists are not lock free, but local to a thread.

**Comment by diraimondo** [comment]
Ok, now it is clear how to bind a mempool to the context of a thread. 
The other question, indeed I was not clear, is if I can use a mempool (specialized for a tuple) to feed the allocation requests of a M_LET macro willing to instantiate some of such tuples.

**Comment by P-p-H-d** [comment]
I am not sure if I understand the question well.
The M_LET macro allocates the temporary variables on the stack, letting the underlying type of the variable decides with its initialization method if it needs some allocation. A tuple won't perform any allocation on its own. 
So you cannot use a mempool specialized for a tuple to feed M_LET as such mempool doesn't exist.

**Comment by diraimondo** [comment]
Ok, I didn't know M_LET macro uses the stack: I thought it used malloc/free (it could, right?). My idea was to use the heap but recycling tuples from a mempool: could it be faster than using the stack?

**Comment by diraimondo** [comment]
Ok, it was a desperate attempt to optimize the code. The use of an advanced allocator like tcmalloc helped a bit without much effort.
Thanks anyway.
