### ISSUE TITLE
No more able to have a container for my own types

### ISSUE THREAD

**Issue by rcarbone** [P-p-H-d/mlib#47]

**Comment by rcarbone** [comment]
Hi Patrick, I have used your superb implementation last year in a my benchmark tool. It outperformed a lot of other implementations.

Today I have updated to latest version but I am no more able to define a container using my own types.

For example this simple program does not compile (I want to have a simple array of pointers to integers)

/* System headers */ 
#include <stdio.h> 
 
/* The implementation */ 
#include "m-array.h" 
 
/* Generate prototypes and inline functions */ 
ARRAY_DEF(rock, int *) 

int main (int argc, char * argv []) 
{ 
  /* Bye bye! */ 
  return 0; 
} 

what I have to do?

**Comment by P-p-H-d** [comment]
Hello, 

And thank you very much for your return!

For your issue, I assume you build in C11 mode (C99 has no issue).
The default oplist (which is used without the third argument) supports only basic C type but doesn't support well pointer (in fact this is the automatic I/O part that is activated in C11 build which doesn't support it at all). You need to tell M*LIB it needs to use it like a pointer like this:

`ARRAY_DEF(rock, int *, M_PTR_OPLIST)
`

**Comment by rcarbone** [comment]
Hi again Patrick,
thank a lot for your suggestion.

It solved some issues but not all. It think a lot of very simple examples should be added to the implementation about how to define a container of standard types, of pointer to standard types,
user-defined types, pointers to user-defined types and so on;
And flags to compile both in C99 and C11 modes.

For example I have a my own type used only for test purpose to initialize and put unique objects in the containers. Please note I have robj_t  no robj_t[1] such all your types.

I would like to define a container of such type How to solve it?
/* System headers */ 
#include <stdio.h> 
/* The implementation */ 
#include "m-array.h" 
/* Object definition */ 
typedef struct robj robj_t; 
struct robj 
{ 
  unsigned   magic;  /* The magic number */ 
  unsigned   ukey;    /* numeric key           */ 
  char        * skey;    /* string key               */ 
  unsigned   uval;     /* numeric value        */ 
  char        * sval;     /* string value            */ 
  robj_t      * obj;       /* self pointer            */ 
  unsigned   slen;     /* strlen of sval         */ 
}; 
 
/* Generate prototypes and inline functions */ 
ARRAY_DEF(rock, robj_t) 
 
/* Generate prototypes and inline functions */ 
int main (int argc, char * argv []) 
{ 
  /* Bye bye! */ 
  return 0; 
} 

ps.  If you are interested the following is final part of the output of my benchmark for rb-tree implementation (mlib used if a 2018 version)
 
                                        A r r i v a l   O r d e r 
 
      Implementation    | mark | # 1 | # 2 | # 3 | # 4 | # 5 | # 6 | # 7 | # 8 | # 9 | #10 | #11 | 
   1: mlib/rbtree           |   90  |   1  |   1   |   1 |   1  |   1  |   1  |   1  |   1 | --- | --- |   1 | 
   2: bsd/rb                  |   72  |   4  |   2   |   3 |   3  |   3  |   3  |   3  |   2 | --- | --- |   4 | 
   3: linwei/avlmini       |   67  |   3  |   4   |   4 |   4  |   5  |   4  |   2  |   3 | --- | --- |   3 | 
   4: wahern/llrb           |   66  |   2  |   3  |   2 |   2  |   2  |   2 |   9   |   9 | --- | --- |   2 | 
   5: fmela/rb                |   51  |   6  |   5  |   7 |   5  |   4  |   6 |   4   |   5 | --- | --- |   6 | 
   6: gdsl/rbtree            |   48  |   5  |   6  |   6 |   7  |   6  |   5 |   5   |   6 | --- | --- |   5 | 
   7: jevans/rb              |   33  |   8  |   7  |   9 |   6  |   9  |   8 |   7    |   4 | --- | --- |   8 | 
   8: libredblack/rbtree |   31  |  10 |   8  |   5 |   8   |   7  |   7 |   6   |   7 | --- | --- |  10 | 
   9: libavl/rb                |   25  |   7  |  10 |   8 |   9  |   8  |   9 |   8    |   8 | --- | --- |   7 | 
  10: jsw/rb                  |   12  |   9  |   9  |  10 |  10 |  10 |  10 |  10 |  10 | --- | --- |   9 | 

This happen if I use

**Comment by P-p-H-d** [comment]
Hi again,

1) I agree that the example section is too small. Thank you for your feedback.

2) For your issue, you need to define the container as:
```
/* Generate prototypes and inline functions */
ARRAY_DEF(rock, robj_t, M_POD_OPLIST)
```
robj_t is a plain old data structure, so the oplist to use is M_POD_OPLIST (which provides basic copy, comparison and hash of structure using memcpy, memcmp, ...).

3) Thank you for sharing your result! It is very interesting.
About your last remark:
a) RBTREE_DEF(mlibrb, robj_t *)
b) RBTREE_DEF(mlibrb, robj_t *, (CMP (cmpobj)))
Definition (a) compares the pointers of the object, and orders the container in the pointer order. I am not sure if it is what you want to do.
Definition (b) compares the object, and the order of the container is the one you defined.

**Comment by rcarbone** [comment]
Hi Patrick,
thanks again for your reply. I will take a deep look asap.

I am currently working on a completely new version of the tool but you can try yourself the old version of the tool at:
     https://github.com/rcarbone/rperf

I am quite sure that people do not remember times but are much interested in ranking. So I implemented 2 main applications:
 * a speed application which uses timing spent to perform a test into a rank and summarize results
 * a battle application, a sort of hash table machine where all implementation under test leave one by one the game until a winner foreach scenario is found

Each application is implemented as a plugin and it is accepted to the battle only if it passed both a valgrind based unit-test and a valgrind-based test-suite.

/rocco

**Comment by P-p-H-d** [comment]
As per your suggestion, I have included in master an example (example/ex-array00.c) which shows how to handle the basic types, pointers, strings and structures as arrays (with their oplist). 

Thank you for the link of your bench. I'll have a look at it.
