### ISSUE TITLE
Supplying references to equal and compare

### ISSUE THREAD

**Issue by jens-totemic** [P-p-H-d/mlib#49]
I'm putting structs into a list like so:
```
typedef struct __MyData {
    int data;
} MyData;

inline bool MyData__equals(const MyData z1, const MyData z2) {
    return z1.data == z2.data;
}

LIST_DEF(MyList, MyData, M_OPEXTEND(M_POD_OPLIST, EQUAL(MyData__equals)))
```

When comparing two list elements, the `MyData__equals` function gets supplied two elements copied by value. Is it somehow possible to supply them as pointers, so they won't be copied through the stack? I have tried to use `M_IPTR` which gets me this:

```
inline bool MyData__equals(const MyData *z1, const MyData z2) {
    return z1->data == z2.data;
}

LIST_DEF(MyList, MyData, M_OPEXTEND(M_POD_OPLIST, EQUAL(MyData__equals M_IPTR)))
```

So I'm half-way there. Is there a way to also get the second value passed as pointer?

**Comment by P-p-H-d** [comment]
The best and simple solution will be to update your definition of the structure (to use the [1] trick) like this:

```
typedef struct __MyData {
    int data;
} MyData[1];

inline bool MyData__equals(const MyData z1, const MyData z2) {
    return z1->data == z2->data;
}

LIST_DEF(MyList, MyData, M_OPEXTEND(M_A1_OPLIST, EQUAL(MyData__equals)))
```

You will still allocate the memory by declaring a variable (global or local) and you will always pass the structure by reference. A consequence is that you'll always need to access the data using '->' instead of '.'.

**Comment by P-p-H-d** [comment]
Another way to do it for only some targeted function is through macro encapsulation:

```
inline bool MyData__equals(const MyData *z1, const MyData *z2) {
    return z1.data == z2.data;
}
#define MyData__equals_val(z1, z2) MyData__equals(&(z1),&(z2))
LIST_DEF(MyList, MyData, M_OPEXTEND(M_POD_OPLIST, EQUAL(MyData__equals_val)))

```

**Comment by P-p-H-d** [comment]
A third solution is to use the new available API transformation:

 ```
inline bool MyData__equals(const MyData *z1, const MyData *z2) {
    return z1->data == z2->data;
}
LIST_DEF(MyList, MyData, M_OPEXTEND(M_POD_OPLIST, EQUAL(API_6(MyData__equals ))))
```
