### ISSUE TITLE
Can you provide a "complex" struct example?

### ISSUE THREAD

**Issue by maxdemarzi** [P-p-H-d/mlib#50]
Say I have a struct with a few uint32_t, a string_t and some json from https://github.com/DaveGamble/cJSON:

`typedef struct rel {
  uint32_t id;
  uint32_t incoming_node_id;
  uint32_t outgoing_node_id;
  string_t type;
  cJSON* properties;
} relationship;`

and you wanted a dynamic array of them:
`ARRAY_DEF(array_relationship, relationship, (INIT(relationship_init),SET(relationship_set),INIT_SET(relationship_init_set),CLEAR(relationship_clear)))`

What would the relationship_init, relationship_set, relationship_init_set and relationship_clear look like to make it work?

**Comment by P-p-H-d** [comment]
Hi,

 You can have something like that:

```
typedef struct rel {
  uint32_t id;
  uint32_t incoming_node_id;
  uint32_t outgoing_node_id;
  string_t type;
  cJSON* properties;
} relationship;

void relationship_init(relationship *obj)
{
  obj->id = 0;
  obj->incoming_node_id = 0;
  obj->outgoing_node_id = 0;
  string_init(obj->type);
  obj->properties = NULL;
}

void relationship_init_set(relationship *obj, const relationship src)
{
  obj->id = src.id;
  obj->incoming_node_id = src.incoming_node_id;
  obj->outgoing_node_id = src.outgoing_node_id;
  string_init_set(obj->type, src.type);
  if (src.properties)
    obj->properties = cJSON_Duplicate(src.properties, true);
  else
    obj->properties = NULL;
}

void relationship_set(relationship *obj, const relationship src)
{
  obj->id = src.id;
  obj->incoming_node_id = src.incoming_node_id;
  obj->outgoing_node_id = src.outgoing_node_id;
  string_set(obj->type, src.type);
  if (obj->properties)
    cJSON_Delete(obj->properties);    
  if (src.properties)
    obj->properties = cJSON_Duplicate(src.properties, true);
  else
    obj->properties = NULL;
}

void relationship_clear(relationship *obj)
{
  string_clear(obj->type);
  if (obj->properties)
    cJSON_Delete(obj->properties);
}

ARRAY_DEF(array_relationship, relationship, (INIT(relationship_init M_IPTR),SET(relationship_set M_IPTR),INIT_SET(relationship_init_set M_IPTR),CLEAR(relationship_clear M_IPTR)))

```

**Comment by P-p-H-d** [comment]
Here is another example [ex-array05](https://github.com/P-p-H-d/mlib/blob/master/example/ex-array05.c)
The only difference is that the structure 'src' is passed by pointer in this case, rather than by value.

**Comment by maxdemarzi** [comment]
Thank you for your help. I was not getting the `M_IPTR` part, this works great.
