### ISSUE TITLE
M_KEEP redefined

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#53]
Seems like one of your internal macros are actually defined in stdlib =)

![image](https://user-images.githubusercontent.com/468323/84528890-2ec15100-ace9-11ea-8f53-ddec76e48f2e.png)

Great work on the project, BTW!

**Comment by vladipus** [comment]
The exact error I get is:
include/mlib/m-core.h:672: error: "M_KEEP" redefined [-Werror]
  672 | #define M_KEEP(n, ...)  M_KEEPI(M_C(M_KEEPI_, n), __VA_ARGS__)

**Comment by P-p-H-d** [comment]
Thank you for your report.

The conflict is in the header malloc.h for an unused feature.
It should be fixed in master. The macros have been renamed in M_KEEP_ARGS (I also apply the same renaming for M_MID & M_SKIP for uniformity).

**Comment by vladipus** [comment]
So FAST, really? Great job, man (guys). Hope, I could help with code someday. It's still kinda difficult for me to get into the advanced macro stuff. =)
