### ISSUE TITLE
Implicit conversion to an unsigned int, when using a typedef

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#54]
I'm getting a strange warning of unsigned int conversion, when using a typedef'ed int32_t (GTSubjectIndex).

![image](https://user-images.githubusercontent.com/468323/84572935-25e28500-ada6-11ea-9f66-3e43b3bc0a53.png)

**Comment by vladipus** [comment]
This warning is raised, even if I use `ARRAY_DEF(GTSubjectIndices, int32_t)`

**Comment by vladipus** [comment]
`ARRAY_DEF(GTSubjectIndices, uint64_t)`

strangely raises that one:

Implicit conversion changes signedness: 'const uint64_t' (aka 'const unsigned long') to 'long long'clang(-Wsign-conversion)

**Comment by P-p-H-d** [comment]
Hi,
You are right. I didn't test with this warning (-Wsign-conversion)
I have fixed your issues with m-core + m-array in master.
I am still fixing other warnings raised in other part of the library.
Thanks.

**Comment by vladipus** [comment]
Thanks a lot! Checking, please wait.

**Comment by vladipus** [comment]
The first issue is now resolved.
`ARRAY_DEF(GTSubjectIndices, uint64_t)` is still issuing a warning. Should I create another issue?

**Comment by P-p-H-d** [comment]
No. Thank you.
It is fixed in master now.

**Comment by vladipus** [comment]
Ok, let me check. At least I can help you with tests for now. Thank you.

**Comment by vladipus** [comment]
Works great now! Good job!

**Comment by P-p-H-d** [comment]
Thank you for your report!
