### ISSUE TITLE
Provide documentation for zero-initalization-safe containers.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#56]
Seems like the array container is safe to be zero-initialized (as a global varable for example). It would be nice to explicitly state this in the documentation, as it may not be actually convenient to initalize global variables at some circumstances.

**Comment by P-p-H-d** [comment]
I am not sure it is a good thing to provide such strong specification. 
In case of incompatible change in the future, the user application would be broken (such strong specifications are what prevent improvement of the STL). Moreover only a few containers support then (array & linked list).

I have a few questions thus:

- In fact, your real need is to automatically initialize & clear a global variable?
- When & How do you perform the free of this global variable?

I can imagine a macro M\_LET\_GLOBAL( ...) that will initialize & clear a global variable, but I cannot make it works if it isn't GCC (or compatible - using attributes constructor / destructor) or C++ (using classic constructor / destructor). And I am not fond of functionality that only works with only one class of compiler (it is ok to optimize for one however but a compatible fallback shall be available).

**Comment by vladipus** [comment]
I see your points and they are valid. If there is still would have to be a finalizing function, it's better to provide an initializing one anyway. I wouldn't rely on any compiler specific functionality also.

**Comment by vladipus** [comment]
I have found a case, that I would suggest as important, optimization-wise. Sometimes it is simpler to zero-initialize your own struct with `memset`. Perhaps, it saves some cycles not to be forced to call `array_init` functions, if the struct has many of those. What do you think?

**Comment by P-p-H-d** [comment]
This technique is a little bit unsafe. you'll even get warnings with this with C++ compilers and I wouldn't be surprised if C compilers introduce such warnings. It is unsafe if the structure has any float.

Moreover, you'll only get a modest speed-up if your structure is big, and it may even bit slower for small structure if the compiler is not smart enough. It may still provide gain in the executable size  but still it won't be much. It is also easier to add a new member in it. But I don't think there are a lot of such kind of structures (with many of arrays).

**Comment by vladipus** [comment]
Fair enough. The floats can get tricky with memsetting. However, the zero-initialization-safe structures (POD-style) can still benefit, including those, defined with a M_POD_OPLIST, since you can be sure that this OPLIST is safe to use for them. What to do you think?

**Comment by vladipus** [comment]
To sum it up, explicitly stating (standardizing) the zero-safety of some of the containers in the documentation would clear things up for the user, whenever he wants those things to be clear =)

**Comment by P-p-H-d** [comment]
I think such a standardization would be good for some designs, in particular one when you want to share some containers in some shared memory (like POSIX shared memory) to communicate fast and quickly between process. But such a need will need a dedicate container (in particular one providing atomic transactions and pointer free).

**Comment by vladipus** [comment]
Good point, a dedicated zero-free and even pointer-free container is a fine (fine-grained actually) feature to have.
Sorry for delay. I'm back in business, man. Saw you've removed the issues as I've failed to review them in time. I'm still gonna do it in near future.

Thanks again for your work.

**Comment by P-p-H-d** [comment]
ARRAY\_INIT\_VALUE(), LIST\_INIT\_VALUE() & LIST\_DUAL\_PUSH\_INIT\_VALUE() have been added in the master branch,
allowing to initialize global variables of array type (as requested in the ticket).
