### ISSUE TITLE
Function 'name##_set_at' could be declared with attribute 'noreturn'clang(-Wmissing-noreturn)

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#59]
I'm getting a new series of new warnings on Clang. =)
Seems like you could use a `__attribute__((noreturn))` with your automatically generated functions.
I'm already using it with mine. Does that sound reasonable for you?

**Comment by vladipus** [comment]
![image](https://user-images.githubusercontent.com/468323/85438679-e5002280-b594-11ea-9cff-6269bc7e76b5.png)

**Comment by vladipus** [comment]
If some of the methods assert (never return) additional compile-time semantic could be useful.

**Comment by P-p-H-d** [comment]
I am not against adding attribute noreturn. But I am confused.
Theses functions **DO** return.... Otherwise they won't be useful :)

**Comment by vladipus** [comment]
I see. So they use some of my noreturn functions, and thus propagate and do not return likewise. Could there be any solution to this? Maybe some API level to specify additional attributes?

**Comment by P-p-H-d** [comment]
I don't understand why you have some noreturn functions that are called by M\*LIB? 
I find it suspicious, and it may be a bug on your side.

**Comment by vladipus** [comment]
The reason for that is that I have some functions defined as:
```c
static inline GT_NO_RETURN_ATTR void GTBelt_set(GTBelt *belt,
                                                const GTBelt *orig)
{
    GT_ASSERT_NEVER_HAPPENS_FORMAT(
        "Copying belts is not supported: %" GT_BELT_ID_PR "<-%" GT_BELT_ID_PR,
        belt->_id, orig->_id)
}
```

**Comment by P-p-H-d** [comment]
Ok
It will be better in this case not to define the functions of the container at all if the used method of the type (SET, ...) is not supported (it will provide a compiler failure rather than a run time failure).
It is already partially supported.
What is the container you use and which methods have you disabled?

**Comment by vladipus** [comment]
I'm using an array with `_init_set` and `_set`  functions calling `abort()`. Basically this means `no copying allowed`.

**Comment by P-p-H-d** [comment]
You only use _push_raw, _push_new or _push_move ? And not _push_back, _push_at?

**Comment by vladipus** [comment]
that is right, I only use `_push_new`

if I omit these methods, I get the following errors:
![image](https://user-images.githubusercontent.com/468323/85788502-c6855d00-b735-11ea-91e2-ff683337563d.png)

**Comment by vladipus** [comment]
These are the only functions in the project that I actually use:
![image](https://user-images.githubusercontent.com/468323/85788718-13693380-b736-11ea-87b6-f68d2e177e04.png)

**Comment by P-p-H-d** [comment]
The array container has been updated in master and supports now if there is no INIT\_SET and/or SET operators in the oplist.
This should allow you to define GTBelts without function with assertion.

**Comment by vladipus** [comment]
That's great! A truly work of art your library is. Checking it right now!

**Comment by vladipus** [comment]
Works fine.
