### ISSUE TITLE
OPLIST macro to define a custom type name for the container.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#60]
I've got some idea for your consideration. It would be nice to have some kind of functionality to define your own container typedef. The standard is to append a `_t` at the end of the container name. My library uses a different approach that should define the type as the name itself. I always have to typedef the container to it afterwards. Is it possible to have some kind of CONTAINER_TYPE macro to define the resulting type? The default would still be `name_t`, if not supplied.

**Comment by P-p-H-d** [comment]
Yes.
I have thought about it but I don't know if I'll go with a global customization or a local customization of the container.

Global one V1 (easiest one -macro shall be defined before inclusion):
```
#define M_USE_TYPENAME(name) name
#include "m-array.h"
ARRAY_DEF(...)
```

Global one V2 (a little bit more complex - macro shall be defined before first definition):
```
#include "m-array.h"
#define M_USE_TYPENAME(name) name
ARRAY_DEF(...)
```

Local one (a little bit more complex -macro is associated to oplist):
```
#include "m-array.h"
#define FT_TYPENAME(name) name
ARRAY_DEF(array_int, int, M_OPEXTEND(M_DEFAULT_OPLIST, TYPENAME(FT_TYPENAME))
```

**Comment by vladipus** [comment]
`OPLIST` solution seems like the most desired one, but the V2 looks like a nice compromise.
define-before-include solutions do not sound like a good design for me (I'm certainly not the most C experienced person out there, though)

**Comment by P-p-H-d** [comment]
Another local one where you specify the name of the type (and its iterator) afterwards:
```
#include "m-array.h"
ARRAY_DEF_AS(array_int, array_int_t, array_int_it_t,  int, M_DEFAULT_OPLIST)
```

I prefer adding another macro because of tuple/variant/funcobbj: they have a variable number of arguments, and this prevent from adjusting the behavior of the _DEF macro in function of it.

**Comment by vladipus** [comment]
The last solution seems like the BEST one to me.
