### ISSUE TITLE
m_core_fscan_bool (and possibly others) have implicit conversion loses integer precision warning

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#61]
![image](https://user-images.githubusercontent.com/468323/85700166-ca3cc380-b6e4-11ea-9d28-e30a9ec23252.png)
Keep on bringing more warnings for your consideration. =) Compiling with Clang 10 under Windows 10.

**Comment by vladipus** [comment]
This one also triggers the warning:
![image](https://user-images.githubusercontent.com/468323/85702135-c4e07880-b6e6-11ea-9336-01d8e6ac9daa.png)

**Comment by P-p-H-d** [comment]
It should be fixed in master.

I am quite tired of this warning ! There are no two compilers that raise it in the same place!

**Comment by vladipus** [comment]
Got it. Thank you. I've finished the refactoring and now start the testing (and closing the issues on success).

**Comment by vladipus** [comment]
O.K. this is fixed now.
