### ISSUE TITLE
Provide the C++ friendliness of the library (with solution)

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#63]
It's not rare when C headers are included in C++ sources. The current state of your library is that it works, but still produces compile-time warnings, that can be suppressed with some additional functionality, so here are some of recipes that I currently use myself. They were a part of doctest library, which in turn has taken them from some other project. Be warned though, that my library's requirements may be more strict than yours, so, please, examine the `#error` macros before using.

Provide an additional header file, detecting the compiler (and language) used:
```c
#pragma once

// This compiler detection is taken from the doctest project.
#define M_COMPILATION_COMPILER(MAJOR, MINOR, PATCH)                           \
    ((MAJOR)*10000000 + (MINOR)*100000 + (PATCH))

// GCC/Clang and GCC/MSVC are mutually exclusive, but Clang/MSVC are not because
// of the 'clang-cl' interface.
#if defined(_MSC_VER) && defined(_MSC_FULL_VER)
#if _MSC_VER == _MSC_FULL_VER / 10000
#define M_COMPILATION_MSVC                                                    \
    M_COMPILATION_COMPILER(_MSC_VER / 100, _MSC_VER % 100,                    \
                            _MSC_FULL_VER % 10000)
#else // MSVC
#define M_COMPILATION_MSVC                                                    \
    M_COMPILATION_COMPILER(_MSC_VER / 100, (_MSC_FULL_VER / 100000) % 100,    \
                            _MSC_FULL_VER % 100000)
#endif // MSVC
#endif // MSVC
#if defined(__clang__) && defined(__clang_minor__)
#define M_COMPILATION_CLANG                                                   \
    M_COMPILATION_COMPILER(__clang_major__, __clang_minor__,                  \
                            __clang_patchlevel__)
#elif defined(__GNUC__) && defined(__GNUC_MINOR__) &&                          \
    defined(__GNUC_PATCHLEVEL__) && !defined(__INTEL_COMPILER)
#define M_COMPILATION_GCC                                                     \
    M_COMPILATION_COMPILER(__GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__)
#endif // GCC

#ifndef M_COMPILATION_MSVC
#define M_COMPILATION_MSVC 0
#endif // M_COMPILATION_MSVC
#ifndef M_COMPILATION_CLANG
#define M_COMPILATION_CLANG 0
#endif // M_COMPILATION_CLANG
#ifndef M_COMPILATION_GCC
#define M_COMPILATION_GCC 0
#endif // M_COMPILATION_GCC

#if M_COMPILATION_CLANG
#define M_COMPILATION_PRAGMA_TO_STR(x) _Pragma(#x)
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_PUSH()                           \
    _Pragma("clang diagnostic push")
#define M_COMPILATION_CLANG_SUPPRESS_WARNING(w)                               \
    M_COMPILATION_PRAGMA_TO_STR(clang diagnostic ignored w)
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_POP()                            \
    _Pragma("clang diagnostic pop")
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_WITH_PUSH(w)                     \
    M_COMPILATION_CLANG_SUPPRESS_WARNING_PUSH()                               \
    M_COMPILATION_CLANG_SUPPRESS_WARNING(w)
#else // M_COMPILATION_CLANG
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_PUSH()
#define M_COMPILATION_CLANG_SUPPRESS_WARNING(w)
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_POP()
#define M_COMPILATION_CLANG_SUPPRESS_WARNING_WITH_PUSH(w)
#endif // M_COMPILATION_CLANG

#if M_COMPILATION_GCC
#define M_COMPILATION_PRAGMA_TO_STR(x) _Pragma(#x)
#define M_COMPILATION_GCC_SUPPRESS_WARNING_PUSH()                             \
    _Pragma("GCC diagnostic push")
#define M_COMPILATION_GCC_SUPPRESS_WARNING(w)                                 \
    M_COMPILATION_PRAGMA_TO_STR(GCC diagnostic ignored w)
#define M_COMPILATION_GCC_SUPPRESS_WARNING_POP() _Pragma("GCC diagnostic pop")
#define M_COMPILATION_GCC_SUPPRESS_WARNING_WITH_PUSH(w)                       \
    M_COMPILATION_GCC_SUPPRESS_WARNING_PUSH()                                 \
    M_COMPILATION_GCC_SUPPRESS_WARNING(w)
#else // M_COMPILATION_GCC
#define M_COMPILATION_GCC_SUPPRESS_WARNING_PUSH()
#define M_COMPILATION_GCC_SUPPRESS_WARNING(w)
#define M_COMPILATION_GCC_SUPPRESS_WARNING_POP()
#define M_COMPILATION_GCC_SUPPRESS_WARNING_WITH_PUSH(w)
#endif // M_COMPILATION_GCC

#if M_COMPILATION_MSVC
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_PUSH() __pragma(warning(push))
#define M_COMPILATION_MSVC_SUPPRESS_WARNING(w) __pragma(warning(disable : w))
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_POP() __pragma(warning(pop))
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_WITH_PUSH(w)                      \
    M_COMPILATION_MSVC_SUPPRESS_WARNING_PUSH()                                \
    M_COMPILATION_MSVC_SUPPRESS_WARNING(w)
#else // M_COMPILATION_MSVC
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_PUSH()
#define M_COMPILATION_MSVC_SUPPRESS_WARNING(w)
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_POP()
#define M_COMPILATION_MSVC_SUPPRESS_WARNING_WITH_PUSH(w)
#endif // M_COMPILATION_MSVC
```

Based on the language and compiler used, you can now specify some basic defines:
```c
#pragma once

#if M_COMPILATION_CPP
#define M_BEGIN_EXTERN_C                                                      \
    extern "C"                                                                 \
    {
#define M_END_EXTERN_C }
#else
#define M_BEGIN_EXTERN_C
#define M_END_EXTERN_C
#endif

// Beginning and ending of every header.
#define M_BEGIN_HEADER                                                        \
    M_COMPILATION_CLANG_SUPPRESS_WARNING_PUSH()                               \
    M_COMPILATION_GCC_SUPPRESS_WARNING_PUSH()                                 \
    M_COMPILATION_CLANG_SUPPRESS_WARNING("-Wold-style-cast")                  \
    M_COMPILATION_GCC_SUPPRESS_WARNING("-Wold-style-cast")                    \
    M_COMPILATION_CLANG_SUPPRESS_WARNING("-Wzero-as-null-pointer-constant")   \
    M_COMPILATION_GCC_SUPPRESS_WARNING("-Wzero-as-null-pointer-constant")     \
    M_BEGIN_EXTERN_C

#define M_END_HEADER                                                          \
    M_END_EXTERN_C                                                            \
    M_COMPILATION_CLANG_SUPPRESS_WARNING_POP()                                \
    M_COMPILATION_GCC_SUPPRESS_WARNING_POP()
```

The begin header and end header macros now should enclose *every* header.

**Comment by P-p-H-d** [comment]
You do love warnings, do you? :)

Well, anyway, a few remarks/questions I have to considered to mature the answer:

* Theses warnings have to be enabled explicitly (there are not included in -Wall and -Wextra) as far as I can see, have they?
* Is there a practical difference between _Pragma("GCC ...") and _Pragma("clang ...")?
* -Wzero-as-null-pointer-constant is not supported in some versions of CLANG (at least 4 and under). I don't know when it has been introduced.
* _Pragma("GCC diagnostic ignored ..") is not working with GCC C++ preprocessor: See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431 ! It is a 8 years old bug which is still not fixed...
* It won't be sufficient to include it in headers. We need also to include in generation macro.
* Is there a difference between CLANG WIN and CLANG LINUX and CLANG MAC on this topic?

**Comment by vladipus** [comment]
Being warnings-free is a nice feature to have, and helps building up a brand's loyalty. It's even more important for library code, since it tends to propagate on the client code it turn. I do like warning free tools (like doctest, which even states that on its main feature page, and you should do it too, btw).

1) They are present for me when running `clang-cl` with the following options `-Wall -Wextra`.
2) There actually is, since `clang-cl` is actually MSVC compliant compiler, still providing its own features, unlike GCC which is by itself only.
3) I don't really know, but I suppose issuing some excessive pragmas won't be an issue, is it?
4) The pragma code that I presented doesn't actually use the `#pragma` directive, but an internal function-like code. The `docstring` library that uses that code is highly portable C++ test suite, so I bet you should not worry about that.
5) That would not necessary. I would actually vote against doing so, since your library should really stay as C library, not C++. It just needs some extra functionality to be warning-free on C++ (i.e. friendly), but not to be used in C++ headers and such directly, since C++ already has std:: containers and boot. So it's up to the user to suppress the warnings. If you'd like you could just provide some basic macro like M_BEGIN and M_END to define some kind of "extra-safe" scope when using your library.
6) Not exactly sure about the Mac, but `clang-cl`, as I said before is just like MSVC with some extra functionality. MSVC, btw, doesn't compile the code using your library at all, event in C-as-C++ mode. At least I couldn't make it work.

**Comment by P-p-H-d** [comment]
It should be taken into account in master.

By the way, only the latest version of MSVC compiles the code. But you need theses options:
 /Zc:preprocessor
 /Zc:__cplusplus
