### ISSUE TITLE
Noting __STDC_NO_THREADS__ in the documentation.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#65]
Seems like C11 implementations (even open-source) are a bit messy on that topic. Even though C11 macros can be defined correctly and accordingly `__STDC_NO_THREADS__` can still be undefined, even if the `threads.h` header is not available. User-defining `__STDC_NO_THREADS__` prior to including `m-mutex.h` could be an answer, perhaps, This still has to be noted in the documentation, since by default on Windows 10, clang-cl, the threading functionality fails to compile (because of the missing header).

**Comment by P-p-H-d** [comment]
Indeed.
I have added this note in the documentation.

**Comment by vladipus** [comment]
A portable CMake sample, for those who are interested, may look like this:

```cmake
include(CheckIncludeFile)
check_include_file("threads.h" HAS_THREADS_H)

if(NOT (HAS_THREADS_H))
target_compile_definitions(${GT_ENGINE_LIB_NAME} PUBLIC __STDC_NO_THREADS__=1)
endif()
```

**Comment by P-p-H-d** [comment]
I think you should not define __STDC_NO_THREADS__ if it is already defined.

**Comment by vladipus** [comment]
That's a wise remark indeed. Hmm, even CMake doesn't seem to support (or explicit) functionality to detect C11 threading: https://cmake.org/cmake/help/latest/module/FindThreads.html What a mess, man. Such a wide-spread functionality seems like a left-over =)
Anyways, with so much hassle, would it be wise to explicitly define a threading used, instead of auto-detecting it in the library? Maybe a user should be able to define some macro like `M_USE_PTHREADS` to state explicitly what he wants?

**Comment by P-p-H-d** [comment]
In master, I have added the support for the user to disable C11 header by defining M_USE_C11_NO_THREADS.

**Comment by vladipus** [comment]
"and as per the standard, the header may not be provided."
Ok, so why not to test for a macros value if it's actually defined (as a precaution)? Judging on that SO answer, there can't be a situation where macro is defined to zero and the header is available.

Anyways, I would actually suggest to add a separate, explicit level of choosing the right threads backend, instead of an exclusive C11 macro, since it would be better compatible with the tools (CMake), as it already has some convenient variables.

CMAKE_USE_WIN32_THREADS_INIT
CMAKE_USE_PTHREADS_INIT
CMAKE_HP_PTHREADS_INIT
There is no C11 threads detection however.

**Comment by vladipus** [comment]
As far as I can tell, it is impossible to reliably detect the C11 thread functionality and CMake also handles the correct linking (to a correct threading library), if you use its variables, so it actually has to work in-sync with your library.

**Comment by P-p-H-d** [comment]
It is possible to detect if C11 thread works. You just need to link a program like the following one at configuration time:
```
#include <threads.h>
 mtx_t lock;
 int main () {
    int err = mtx_init(&lock, mtx_plain);
    mtx_destroy(&lock);
   return 0;
}
```
I don't know how to do it in cmake however.

**Comment by vladipus** [comment]
You can use that macro to test-compile the source: https://cmake.org/cmake/help/latest/module/CheckCSourceCompiles.html

The problem with your solution is still present, since the system may have several options of threading for the user, some of them may also require linker flags, but your library is in-controllable in that matter and just overrides any behavior with its auto-detection. Do you get me?

**Comment by P-p-H-d** [comment]
Taken into account on master. you have the new user macro:
M_USE_THREAD_BACKEND

**Comment by vladipus** [comment]
I've found it more usable to limit the auto-detection just in case of C11 threads with some external CMake tests like so.
![image](https://user-images.githubusercontent.com/468323/103403476-4bc45100-4b61-11eb-883f-a732593abaac.png)
So the M_USE_NO_C11_THREADS macro is an additional user-level customization. The other two choices should still be auto-detected by the library.

**Comment by vladipus** [comment]
![image](https://user-images.githubusercontent.com/468323/103404963-7ebd1380-4b66-11eb-969a-871db20e072b.png)
or maybe something like that

**Comment by vladipus** [comment]
Ended up using to not introduce excessive prefixes
![image](https://user-images.githubusercontent.com/468323/103405560-99908780-4b68-11eb-8055-f81dfed361e8.png)

**Comment by P-p-H-d** [comment]
I think you only need this because the platform you are using is broken. It claims to be C11 compliant but fails to do so...
I don't plan on adding workaround for such broken platform. You should open a bug report on clang for such behavior (their default target is not working).

Moreover, it should be fixed soon in the future since official support of C11 is coming in MSVC: 
https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/
You can force M_USE_THREAD_BACKEND until it becomes official.

**Comment by vladipus** [comment]
Got it. I usually get along with the status quo myself. Working with what *should* be instead of what it is is kinda hard ;)
