### ISSUE TITLE
Intrusive shared pointer mis-behavior (according to docs)

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#66]
From the documentation:
The object oplist is expected to have the following operators (CLEAR and DEL), otherwise *default operators are used*.

This, however, seems not true, as the `init_new` (the documentation sample is also wrong on this one, calling it just `_new`) function is not generated at all, if a user doesn't provide a NEW in the OPLIST.

This OPLIST produces the needed `init_new` function:
(NEW(M_MEMORY_ALLOC), CLEAR(my_clear M_IPTR))
This however does *NOT* but should (if to believe the docs):
(CLEAR(my_clear M_IPTR))

**Comment by P-p-H-d** [comment]
Indeed.
The documentation & the code is wrong. 
It shall only be define is the INIT is defined in the oplist and the NEW method has not been disabled.
The code & documentation have been updated.

**Comment by vladipus** [comment]
This is not completely fixed. I created a PR for that one.

**Comment by vladipus** [comment]
Fixed in https://github.com/P-p-H-d/mlib/pull/73
