### ISSUE TITLE
Warnings caused by m-mutex.h

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#71]
I got the following warnings while using `m-mutex.h`:
```
[build] mlib/m-mutex.h(168,9): warning: macro name is a reserved identifier [-Wreserved-id-macro]
[build] #define _WIN32_WINNT  _WIN32_WINNT_VISTA
[build]         ^
[build] mlib/m-mutex.h(170,10): warning: non-portable path to file '<Windows.h>'; specified path differs in case from file name on disk [-Wnonportable-system-include-path]
```

The second one seems like an easy fix by changing a single (first) letter.
The first one may be a bit difficult, but you could use the push/pop pragma macros, that I suggested before.

**Comment by P-p-H-d** [comment]
1) Yes
2) I also need to use the same mechanism as the case of this header is not standardize and can change across the vendors.

**Comment by vladipus** [comment]
1. Are you? Seems like this is the only warning I get, actually.
2. I think you should support the most popular (latest) Windows convention.

**Comment by vladipus** [comment]
2. Fixed in https://github.com/P-p-H-d/mlib/pull/73

**Comment by P-p-H-d** [comment]
Taken into account in master.

For information, mingw defines windows.h whereas MSVC defines Windows.h

**Comment by vladipus** [comment]
Hmm, that's interesting. Will take into account and test.
