### ISSUE TITLE
Lot's of ISO C99 requires at least one argument for the "..." warnings.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#74]
`warning: ISO C99 requires at least one argument for the "..." in a variadic macro`
![image](https://user-images.githubusercontent.com/468323/86488649-695b5e00-bd6a-11ea-8764-bb81dbfb4d10.png)

**Comment by P-p-H-d** [comment]
Strange. Looks like a compiler bug.
What is the compiler and its version? Do some other test generate this error?

**Comment by vladipus** [comment]
This is under MSYS2. The compilation command is: `cc -std=c99 -Wall -W -pedantic -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wswitch-default -Wswitch-enum -Wcast-align -Wpointer-arith -Wbad-function-cast -Wstr                                                ict-overflow=5 -Wstrict-prototypes -Winline -Wundef -Wnested-externs -Wcast-qual -Wshadow -Wunreachable-code -Wlogical-op -Wstrict-aliasing=2 -Wredundant-decls -Wold-style-definition -Wno-unused                                                -function -ftrapv -Wsign-conversion  -I.. -g -pthread test-malgo.c -o test-malgo.exe`
The `cc --version` output is as follows:
```
cc --version
cc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by P-p-H-d** [comment]
I cannot reproduce the problem (See https://github.com/P-p-H-d/mlib/runs/837501754?check_suite_focus=true for CI on MSYS2).
The command line is a little bit different however.
Do some other test generate this error?

**Comment by P-p-H-d** [comment]
I can reproduce the issue on linux with your version https://github.com/vladipus/mlib.git however 
It seems the issue is in your path :)

**Comment by vladipus** [comment]
Lol, sorry then. Let me check this out.

**Comment by vladipus** [comment]
You were right. There were some `M_C` using mistakes, I've made. Sorry for taking your time. The issue is now fixed in my master.
