### ISSUE TITLE
Assertion during C-string hashing.

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#78]
I get an assertion when using a C-string oplist in a dictionary. This is caused by m_core_hash, which is used by default. The check for alignment fails to be explicitly: `assert ( (( (uintptr_t)p & (sizeof(uint64_t)-1) ) == 0) || (length <= sizeof(uint32_t)));`
The C-string's address is 0x00007ff79367a50c which is not 64-bit aligned really. The string in question is not allocated dynamically, it's a literal value.

**Comment by vladipus** [comment]
Seems like the C-string literals are not obliged to be aligned at all.

**Comment by vladipus** [comment]
And it seems like you're aware of this: 
![image](https://user-images.githubusercontent.com/468323/100542308-15da3700-325a-11eb-88a3-5e86dc13f1f0.png)
This renders using a dictionary with string literals unusable, which is kinda wide usage actually

**Comment by vladipus** [comment]
I have added a Dan Bernstein's hashing to my branch:

![image](https://user-images.githubusercontent.com/468323/100544562-bedb5e80-3267-11eb-970f-677943e9a464.png)

**Comment by P-p-H-d** [comment]
Indeed. 

I have fixed this in master, pretty much like you propose but I am using the internal HASH infrastructure to let the user select the hash function.

Thank you for your report (and proposal).

**Comment by vladipus** [comment]
That's cool you have those additional flexibility with those hashing macro terms. I've now accomodated your method and also've added XOR version of DJB as an addition to existing presets.
![image](https://user-images.githubusercontent.com/468323/100552026-86527980-3295-11eb-94c7-e65eb7a7f003.png)

**Comment by vladipus** [comment]
Also, I see you've removed the M_CSTR_HASH function which may be a good idea considering the new function is specific, but I would personally advocate for still naming it `m_core_cstr_hash` instead of `m_core_str_hash` since cstr is more explicit and clear to work with C-strings (just like the former macro is).

**Comment by P-p-H-d** [comment]
Done
