### ISSUE TITLE
m-atomic implemented using mutex never destroys the mutex

### ISSUE THREAD

**Issue by snlls** [P-p-H-d/mlib#79]
Using compiler that does not support c11 atomics like tcc with clib that supports c11 threads.h.
atomic_init in m-atomic.h initializes mutex using m_mutex_init but there's no m_mutex_clear anywhere.
Not sure if this is real problem at least valgrind didn't give warning when I tested m-atomics with tcc + glibc.

**Comment by P-p-H-d** [comment]
This is a known limitation of this transition layer. And there is nothing we can do against it. In practice, 

* I hope that all compilers will provide such a useful header as stdatomic
* the mutex destroy function is generally a no-op function that does nothing except setting internal fields.

**Comment by vladipus** [comment]
Have you seen an atomic implementation of this lib I've sent you recently?
https://gitlab.inria.fr/gustedt/p99/-/tree/master/p99
Seems like it has a low level per-architecture atomic implementation using asm. Good stuff.

**Comment by P-p-H-d** [comment]
I already know P99 library (See README!). 
Its atomic layer supports only GCC (or compatible), or a compiler for X86/ARM which is compatible with GCC ASM syntax. It was written when there wasn't any stdatomic header in GCC. This is not generic enough to be used as a fallback layer however.

**Comment by vladipus** [comment]
Well, actually it seems like it has a separate implementation using stdatomic.h exactly. Here, take a look:
![image](https://user-images.githubusercontent.com/468323/100867231-f259fb00-34aa-11eb-8aaa-c3a0157cd54f.png)

You have to admit, that in fact this really IS a possible solution - to implement atomics natively, when there is no stdatomic.h. Is GCC syntax the only trouble about P99 here?

**Comment by P-p-H-d** [comment]
Yes it is a viable alternative :)

>Is GCC syntax the only trouble about P99 here?

The only compiler I know which is compatible with GCC asm syntax but doesn't provide stdatomic is tcc.

**Comment by snlls** [comment]
I agree with that it is not duty of library to provide something that is compilers job and generating assembly is compilers job.
I made this issue thinking that the library could satisfy safety checking tools.
@P-p-H-d mentioned that mutex destroying is basically nop which I thought but I don't have know good knowledge in this area.
This should continued in another issue if needed.
