### ISSUE TITLE
Overflow issue in bit set

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#81]
I'm merging your recent commits to my branch and found this:
![image](https://user-images.githubusercontent.com/468323/102770102-a48f2f00-4394-11eb-94e4-0d81a9330625.png)
You could use something like this, perhaps:
![image](https://user-images.githubusercontent.com/468323/102770162-c092d080-4394-11eb-81d4-7598b6026aa1.png)

**Comment by P-p-H-d** [comment]
Indeed. Thank you for your report.
It is fixed in master.
