### ISSUE TITLE
Naming Critique

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#82]
As I'm refactoring the library in my separate branch (also thinking about renaming it to avoid the confusion), I'm thinking more and more about renaming the internal macros, ending with `I`. Prefixing with `_` is a lot better than suffixing with `I`, because those macros actually clutter the global completion namespace. So when you try to auto-complete something like TUPLE, a lot of internal "garbage" macros appear in the list, which is not really useful.

Another thing is that certain macros of the library are actually missing the `M_` prefix, which in turn clutter the global namespace, which should be system- or user-defined.

I hope you don't mind some critique from the actual user of your tech ;)

**Comment by vladipus** [comment]
The new `_ct` suffix for type aliases is also confusing. Does that mean "constant type"? Well, that is even more vague, since the constant may actually mean `const`. You could also prefix the internally used type alias with an underscore, IMO.

**Comment by vladipus** [comment]
I think this is also a typo (m-shared.h):
![image](https://user-images.githubusercontent.com/468323/103021147-bfab9b80-455a-11eb-9b75-99d8ae1cfc6a.png)

**Comment by P-p-H-d** [comment]
> I'm thinking more and more about renaming the internal macros, ending with I. Prefixing with _ is a lot better than suffixing with I, because those macros actually clutter the global completion namespace. So when you try to auto-complete something like TUPLE, a lot of internal "garbage" macros appear in the list, which is not really useful.

Prefixing with _  is illegal as per the C standard. It is a reserved prefix:

>All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use (§7.1.3)
> All identifiers that begin with an underscore are always reserved for use as identifiers with file scope in both the ordinary and tag name spaces (§7.1.3)

Future version of the norm lists more exactly the reserved pattern in §J.6.1:

>_[a-zA-Z_][a-zA-Z0-9_]*

Prefixing with something else than may be better indeed for auto-completion (even if TUPLE_ should only propose valid macros).

>certain macros of the library are actually missing the M_ prefix, which in turn clutter the global namespace, which should be system- or user-defined.

Which one for example?

>Does that mean "constant type"?
 No. The suffix _ct indicates a confidential type (not exported)

>I think this is also a typo (m-shared.h):

 Yes, indeed. There is two '_' in the suffix. However, this confidential type is not used in the oplist, so there is no impact.
 So, I'll remove theses useless types instead. Thanks.

**Comment by vladipus** [comment]
One more consideration from me is about C-string methods, `string_get_str` for example. This is opinionated really, but I would personally call those methods with something like cstr instead of str, as str is really confusing - your own string type is also starting with str.

**Comment by vladipus** [comment]
> Prefixing with _ is illegal as per the C standard. It is a reserved prefix:

Are you talking about a single underscore or double underscore? I think the former is fine, as I'm using it currently without any warnings while using the strictest level of warning generation.

**Comment by vladipus** [comment]
this is even more confusing with general-purpose methods like `_in_str` where no C-string is present....

**Comment by P-p-H-d** [comment]
> Are you talking about a single underscore or double underscore? I think the former is fine, as I'm using it currently without any warnings while using the strictest level of warning generation.

Yes. More exactly, as per the standard (see the extract of the standard in my previous comment):
* underscore + underscore : reserved for anything. 
* underscore + uppercase letter : reserved for anything
* underscore + lowercase letter: reserved for anything except macro, label of goto and members of  structures  or  unions

underscore + digit is not reserved however.

>this is even more confusing with general-purpose methods like _in_str where no C-string is present....

 Yes, naming is not perfect. :)
 In particular string_get_str which is not related to cstr at all.

**Comment by vladipus** [comment]
I suggest you ditch the _str methods for FILE and just rename them to _stream or _file. that's what I'm going to to in my branch, at least. =)

**Comment by P-p-H-d** [comment]
>So when you try to auto-complete something like TUPLE, a lot of internal "garbage" macros appear in the list, which is not really useful.

I try changing the prefix of the internal macros (so that it start with something). But the auto completion I used (VS code) is "too smart" and still presents then even if they start with another prefix. So the renaming was useless (and not committed).

**Comment by vladipus** [comment]
I'd suggest you could use something simpler like read\write serialize\deserialize. those are also pretty standard these days.

**Comment by P-p-H-d** [comment]
For internal macro naming, I think I'll use the following rule:

* M_ + F(container_name) + _ + macro name

with F transform a little bit the container name (preventing the automatic completion to works). Like this for list:

* #define M_L1ST_DEF_P4(....)


For generated internal functions, I think I will change the naming as per:

* M_C3(m_ + F(comtainer_name) + _, name, _function_name)

**Comment by vladipus** [comment]
Well, it would be better to auto-complete starting at M_<list>. The list should include "public" entities only then, with no internal "garbage" terms.

`M_L1ST_DEF_P4` looks rather scary, man)) Better use some hexadecimal representation of the name's symbols (joking). Why not choose some kind of uncommon prefix. I'm currently using a small `i` letter for my prefixes and it does just fine.

M_ ... public stuff for the end user.
iM_ ... lib's development area

Isn't the `m_` prefix historically relates to members?

**Comment by P-p-H-d** [comment]
Yes, it is a little bit strange.
Unfortunately, the analyzer of the auto-complete function of some IDE (example Visual Code) don't just take the prefix to complete but tries to find a match even if the prefix doesn't match. So even if I start a macro with M_i_LIST_something, when I write LIST_, I will still have M_i_LIST_something as a potential match. The only thing I found which works is to rewrite completely the prefix LIST into something else (here L1ST). I don't know how to inform the auto-complete function that a symbol shall not be auto-completed, or to inform it of a kind of "priority" in the symbols. 

The m_ prefix is indeed used by a lot of C++ code to identify the members of a class.

**Comment by vladipus** [comment]
My personal opinion is that changing the prefix is "good enough" as changing the name to l33dspeak is "too much".

**Comment by P-p-H-d** [comment]
All the public API have been put in the M_ namespace. All the internal API have been put in their respective namespace.
A wrapper to the old names is provided (which is enabled by default and can be disabled by defining M\_USE\_SMALL\_NAME to 0 before including any header file).

Planning:

* for this version, keep the wrapper to the old name and enable it.
* for the next version, keep the wrapper to the old names and disable it.
* the the next next version, remove the wrapper.

The renaming of the \_str suffix has been put in its own ticket (#99)
