### ISSUE TITLE
_previous in m-rbtree.h is actually next

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#83]
while merge-scanning your branch, I've found a possible issue. Is that a correct code for previous or a typo?

![image](https://user-images.githubusercontent.com/468323/103029674-597b4480-456b-11eb-8cdb-c0b909cf99ef.png)

**Comment by P-p-H-d** [comment]
This is the correct code. The second parameter of _int_next indicates the direction.

**Comment by vladipus** [comment]
I see.. was not sure about that. Thank you.
