### ISSUE TITLE
Possible issue in m-core.h

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#84]
![image](https://user-images.githubusercontent.com/468323/103141583-5917b080-4707-11eb-8801-0b8760303014.png)
Why this doesn't utilize the 'string' macro argument really? maybe the arg should be renamed to 'str'?

**Comment by P-p-H-d** [comment]
Because it is a bug !  :) 
Thank you. It is fixed now, with a proper test case too.

**Comment by vladipus** [comment]
A reasonable fix, that I've also implemented myself. Good job! Closing the issue.
