### ISSUE TITLE
Wrong implementation for set_cstr for bounded strings

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#86]
Indirectly they would use strncpy_s, but that method DOES NOT allow truncating, which seems needed by the semantic of your method.

**Comment by vladipus** [comment]
![image](https://user-images.githubusercontent.com/468323/103232950-dd0eaa00-494c-11eb-873f-385fc2268e4a.png)
this implementation also seems off and risky, since the last argument is actually count that could be used as s1[count]

**Comment by vladipus** [comment]
Maybe something like that would do?
![image](https://user-images.githubusercontent.com/468323/103234000-9a9a9c80-494f-11eb-987b-8fbde3b4829a.png)

**Comment by vladipus** [comment]
Another problem is that strcpy_s guarantees null-termination, but your bound strings may be non-null terminated.

**Comment by vladipus** [comment]
Hmm, you are using strlen in you bounded string size method. That is strange and contradicts with my statement above. Now I see you have max_size + 1 as an array. But you still have to refactor the usage of strncpy

**Comment by vladipus** [comment]
You can even end up with an invalid state since currently:
![image](https://user-images.githubusercontent.com/468323/103234470-cc603300-4950-11eb-8cef-e54e1035c276.png)

**Comment by vladipus** [comment]
You could just 
![image](https://user-images.githubusercontent.com/468323/103234584-177a4600-4951-11eb-9cbd-f0ab1976f051.png)
or maybe rewrite the m_core_strncpy to M_core_strncpy_s and use it everywhere afterwards.

**Comment by vladipus** [comment]
![image](https://user-images.githubusercontent.com/468323/103235904-5231ad80-4954-11eb-87b9-04bb4656a443.png)
this method is also implemented incorrectly. the size of the destination buffer can't be removed that simply and the m_core_strncat is also wrong in case of using strncat_s, semantically wrong.

**Comment by vladipus** [comment]
An interesting thing. At least in debug build. The strncpy_s actually may write data past zero terminator, so it mast be saved manually and restored (for OOR compatibility.

**Comment by P-p-H-d** [comment]
The issue with strncpy_s and strncat_s should be fixed in master.
This is strange however. All the tests already passed with Visual, and they did trigger this behavior of truncation...
So I don't know why they succeed...

>this method is also implemented incorrectly. the size of the destination buffer can't be removed that simply 

Which method?

**Comment by P-p-H-d** [comment]
> This is strange however. All the tests already passed with Visual, and they did trigger this behavior of truncation...
So I don't know why they succeed...

It is because there was a constraint violation (as you notice), the default runtime handler is called which terminates the program and returns a **successful** termination instead of an error to the caller!

**Comment by vladipus** [comment]
> Which method?
bounded string's equal str p

**Comment by vladipus** [comment]
Are you sure about your re-implementation? I've coped with the issue with _s variants. Seems like it is not that bad of an idea to use the secure methods on the bounded strings, since their size is statically defined.

**Comment by P-p-H-d** [comment]
>Which method?
bounded string's equal str p

I see no issue with \_equal\_str\_p of bounded string.

>Are you sure about your re-implementation? 

As sure as the tests passed

**Comment by vladipus** [comment]
> I see no issue with _equal_str_p of bounded string.

In case you've also reimplemented the cat method yourself, there might be no issue. But there WAS one.



> As sure as the tests passed

I've implemented _s variants through non-_s like so and all tests have also passed ;)
![image](https://user-images.githubusercontent.com/468323/103352465-57f3d400-4ab7-11eb-8434-6f9c02c13ef7.png)

**Comment by P-p-H-d** [comment]
>In case you've also reimplemented the cat method yourself, there might be no issue. But there WAS one.

 Yes, the service that used the cat method was wrong. But _equal_str_p doesn't use this cat method :)

**Comment by vladipus** [comment]
Maybe I've misrememeber =)
Ok, closing the issue.
