### ISSUE TITLE
M_EMPTY_P(max) doesn't work

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#87]
Subject. Using M_EMPTY_P(max) or (min) doesn't work cause of std macro min() max() definition.

**Comment by P-p-H-d** [comment]
True
I don't know how to make it works without breaking other detection.
I'll update the documentation to state this limitation.

**Comment by vladipus** [comment]
Me too. Tried many things, substitutions, etc, but only got partial M_EMPTY_P support, braces were not supported. Ended up using a simpler version of M_EMPTY_P that I've called M_EMPTY_TOKEN_P

**Comment by vladipus** [comment]
Just to let you know, you could also tell user to use NOMINMAX macro to undef those pesky macros.

**Comment by P-p-H-d** [comment]
There is also the UNDERFLOW & OVERFLOW macros in windows.h that may generate illegal code (I get this issue recently).
But I think it is outside the scope of the library.
