### ISSUE TITLE
Is it actually possible to create a fixed-size looping buffer?

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#89]
Seems like m-buffer actually is not suitable since it always rewrites the last element without any looping.

**Comment by P-p-H-d** [comment]
Yes, it is possible. It is indeed m-buffer (BUFFER_DEF with BUFFER_UNSAFE)
Why do you think it is not suitable?

**Comment by vladipus** [comment]
I would imagine that a ring fixed-size buffer is something that loops its new last element all over again. Your implementation just rewrites the count - 1 element when the buffer is full.

**Comment by P-p-H-d** [comment]
I am not sure to understand what you mean.
BUFFER\_DEF with a BUFFER\_QUEUE implements a ring buffer as explained here: https://en.wikipedia.org/wiki/Circular_buffer

**Comment by vladipus** [comment]
Does start and end pointers actually change in your implementation?

**Comment by P-p-H-d** [comment]
Yes

**Comment by vladipus** [comment]
What happens when you push an element to a full queue?
I want a thread-unsafe ring-buffer and using BUFFER_PUSH_OVERWRITE also. The pushing seems to always overwrite the last element (count - 1)

**Comment by vladipus** [comment]
I seem to miss the point, maybe. is BUFFER_PUSH_OVERWRITE mandatory for thread-unsafe buffers?

**Comment by P-p-H-d** [comment]
> What happens when you push an element to a full queue?

 It depends on the configuration of the queue. It may:
* block until the queue is not full (if BUFFER_THREAD_SAFE)
* overwrite the youngest element if BUFFER_PUSH_OVERWRITE 
* return a failure otherwise.

>I want a thread-unsafe ring-buffer and using BUFFER_PUSH_OVERWRITE also. The pushing seems to always overwrite the last element (count - 1)

 This is what BUFFER_PUSH_OVERWRITE  does (overwrite the youngest element in case of buffer full) to avoid blocking.

>is BUFFER_PUSH_OVERWRITE mandatory for thread-unsafe buffers?

 No

**Comment by vladipus** [comment]
Ok, I now seem to get it. Thank you.
But it still looks kinda un-optimal that atomic is used in a thread-unsafe version.
what do you think?
![image](https://user-images.githubusercontent.com/468323/107208268-6b794f80-6a12-11eb-9e81-661548d1b057.png)

**Comment by P-p-H-d** [comment]
It is true! Thanks. I have opened an issue on it: #90
