### ISSUE TITLE
BUFFER_DEF / BUFFER_THREAD_UNSAFE: performance issue

### ISSUE THREAD

**Issue by P-p-H-d** [P-p-H-d/mlib#90]
When defining a buffer using BUFFER_DEF with the policy BUFFER_THREAD_UNSAFE, the number of elements in the queue is still an atomic_ulong whereas it is not needed (an unsigned long is more than good enough). This has a bad impact on performance.

To overcome this limitation, we need to do preprocessing conditional code (M_IF) and a solution like the one in m-shared (see SHAREDI_ATOMIC_OPLIST & SHAREDI_INTEGER_OPLIST). To factorize in m-core.h. But it needs to be able to handle preprocessing conditional code on policy (buffer_policy_e) which is not supported.

Another solution is to duplicate the field number[] and to use the right one in function of the policy, which increases the size of the structure with not needed fields (in particular for BUFFER_THREAD_UNSAFE).

Another problem is that the size "unsigned long" seems too big. There is no need for a fixed ring buffer communication of more than 2^32 elements on a 64 bits system. So an 'unsigned int' should be enough. On ARM32, the cost as an atomic operation on 64 bits integer is way higher than on 32 bits integer. To consolidate.

**Comment by vladipus** [comment]
Widening the structure size is totally fine for me, as long as its internal structure size. 4-8 bytes is nothing comparing to the size of the buffer itself, so don't hesitate to do it that way.
