### ISSUE TITLE
string_t: extremely confusing methods names: string_clean and string_clear

### ISSUE THREAD

**Issue by skotopes** [P-p-H-d/mlib#97]
I found that me and my team mates are constantly confusing string_clean/string_clear, no matter how many times we bring this topic we do it again and again.

We'd like to propose rename:

- string_clear -> string_free / string_release

Also why not traditional alloc/free?

**Comment by P-p-H-d** [comment]
The _clean methods have been removed from the master branch.

**Comment by skotopes** [comment]
Awesome, thank you very much )
